/*
 *  Sistema de Asistencia de Control Bancario
 *  SACOBA
 *  
 *  Marcela Cascante Quiros
 *  Diego Delgado Cerdas
 *  Alejandro Loaiza Arguedas
 *  Jose David Mora Loria
 */
package sacoba.cliente;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sacoba.servidor.ClienteServidor;
import sacoba.servidor.beans.Notificacion;

/**
 *
 * @author ulacit
 */
public class CajaView extends Cliente {

    /**
     * Creates new form PuertaView
     */
    public CajaView() {
        super();
        initComponents();
    }

    @Override
    public void run() {
        while (true) {
            try {
                // Recibe un dato de entrada
                String entrada = in.readUTF();
                System.out.println(entrada);
                String[] datos = entrada.split(";"); // Divide los datos de la entrada en cada ';'

                switch (Notificacion.convertirValor(Integer.parseInt(datos[0]))) {
                    case CLIENTE_A_CAJA:
                        //liberarCaja();
                        break;
                    default:
                        break;
                }
            } catch (IOException ex) {
                Logger.getLogger(ClienteServidor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new sacoba.vista.PanelConFondo("fondo_panel.png");
        lblTitulo = new javax.swing.JLabel();
        panelUsuario = new sacoba.vista.PanelConFondo("fondo_panel.png");
        lblTitulo2 = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        txtNombreUsuario = new sacoba.vista.TransparentTextField();
        btnVolver = new sacoba.vista.PanelConFondo("flecha-volver.png");
        lblVolver = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        txtSecuencia = new sacoba.vista.TransparentTextField();
        lblUsuario3 = new javax.swing.JLabel();
        txtTramite = new sacoba.vista.TransparentTextField();
        btnLiberar = new sacoba.vista.PanelConFondo("avanzar.png");
        lblLiberar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 650));
        setSize(new java.awt.Dimension(950, 650));

        lblTitulo.setFont(LETRA_TITULO);
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Asistencia de Control Bancario");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTitulo.add(lblTitulo);
        lblTitulo.setBounds(10, 0, 880, 50);

        lblTitulo2.setFont(LETRA_TEXTO_1);
        lblTitulo2.setText("Próximo cliente:");
        panelUsuario.add(lblTitulo2);
        lblTitulo2.setBounds(90, 90, 250, 40);

        lblUsuario1.setFont(LETRA_TEXTO_2);
        lblUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario1.setText("Nombre:");
        panelUsuario.add(lblUsuario1);
        lblUsuario1.setBounds(100, 180, 150, 30);

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setToolTipText("Ingrese un usuario");
        txtNombreUsuario.setFont(LETRA_TEXTO_2);
        panelUsuario.add(txtNombreUsuario);
        txtNombreUsuario.setBounds(260, 180, 240, 30);

        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        panelUsuario.add(btnVolver);
        btnVolver.setBounds(40, 40, 50, 50);

        lblVolver.setFont(LETRA_TEXTO_3);
        lblVolver.setText("Volver");
        panelUsuario.add(lblVolver);
        lblVolver.setBounds(100, 50, 160, 30);

        lblUsuario2.setFont(LETRA_TEXTO_2);
        lblUsuario2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario2.setText("Secuencia:");
        panelUsuario.add(lblUsuario2);
        lblUsuario2.setBounds(100, 140, 150, 30);

        txtSecuencia.setEditable(false);
        txtSecuencia.setToolTipText("Ingrese un usuario");
        txtSecuencia.setFont(LETRA_TEXTO_2);
        panelUsuario.add(txtSecuencia);
        txtSecuencia.setBounds(260, 140, 110, 30);

        lblUsuario3.setFont(LETRA_TEXTO_2);
        lblUsuario3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario3.setText("Trámite:");
        panelUsuario.add(lblUsuario3);
        lblUsuario3.setBounds(100, 220, 150, 30);

        txtTramite.setEditable(false);
        txtTramite.setToolTipText("Ingrese un usuario");
        txtTramite.setFont(LETRA_TEXTO_2);
        panelUsuario.add(txtTramite);
        txtTramite.setBounds(260, 220, 240, 30);

        btnLiberar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLiberarMouseClicked(evt);
            }
        });
        panelUsuario.add(btnLiberar);
        btnLiberar.setBounds(720, 240, 70, 60);

        lblLiberar.setFont(LETRA_TEXTO_3);
        lblLiberar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLiberar.setText("Liberar caja");
        panelUsuario.add(lblLiberar);
        lblLiberar.setBounds(680, 300, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLiberarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLiberarMouseClicked
        // TODO Enviar peticion al servidor y refrescar contenido del panel
    }//GEN-LAST:event_btnLiberarMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        new CajaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sacoba.vista.PanelConFondo btnLiberar;
    private sacoba.vista.PanelConFondo btnVolver;
    private javax.swing.JLabel lblLiberar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblVolver;
    private sacoba.vista.PanelConFondo panelTitulo;
    private sacoba.vista.PanelConFondo panelUsuario;
    private sacoba.vista.TransparentTextField txtNombreUsuario;
    private sacoba.vista.TransparentTextField txtSecuencia;
    private sacoba.vista.TransparentTextField txtTramite;
    // End of variables declaration//GEN-END:variables
}
