/*
 *  Sistema de Asistencia de Control Bancario
 *  SACOBA
 *  
 *  Marcela Cascante Quiros
 *  Diego Delgado Cerdas
 *  Alejandro Loaiza Arguedas
 *  Jose David Mora Loria
 */
package sacoba.cliente;

import javax.swing.JOptionPane;
import sacoba.vista.VentanaBase;

/**
 *
 * @author Marce
 */
public class CajaLogin extends VentanaBase {

    /**
     * Crea una ventana de login para el cliente Caja
     */
    public CajaLogin() {
        initComponents();
        soloLetras(txtUsuario);
        soloNumeros(txtCaja);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new sacoba.vista.PanelConFondo("fondo_panel.png");
        lblTitulo = new javax.swing.JLabel();
        panelUsuario = new sacoba.vista.PanelConFondo("fondo_panel.png");
        lblTitulo2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        txtUsuario = new sacoba.vista.TransparentTextField();
        txtPasswd = new sacoba.vista.TransparentPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblCaja = new javax.swing.JLabel();
        txtCaja = new sacoba.vista.TransparentTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVolver2 = new sacoba.vista.PanelConFondo("flecha-volver.png");
        lblVolver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 650));
        setSize(new java.awt.Dimension(950, 650));

        lblTitulo.setFont(LETRA_TITULO);
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Asistencia de Control Bancario");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTitulo.add(lblTitulo);
        lblTitulo.setBounds(10, 0, 880, 50);

        lblTitulo2.setFont(LETRA_TEXTO_1);
        lblTitulo2.setText("Ingreso al sistema");
        panelUsuario.add(lblTitulo2);
        lblTitulo2.setBounds(90, 100, 250, 40);

        lblUsuario.setFont(LETRA_TEXTO_2);
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Contraseña*:");
        panelUsuario.add(lblUsuario);
        lblUsuario.setBounds(150, 210, 180, 30);

        lblUsuario1.setFont(LETRA_TEXTO_2);
        lblUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario1.setText("Usuario*:");
        panelUsuario.add(lblUsuario1);
        lblUsuario1.setBounds(150, 170, 180, 30);

        txtUsuario.setToolTipText("Ingrese un usuario");
        txtUsuario.setFont(LETRA_TEXTO_2);
        panelUsuario.add(txtUsuario);
        txtUsuario.setBounds(340, 170, 200, 30);

        txtPasswd.setForeground(new java.awt.Color(0, 0, 0));
        txtPasswd.setToolTipText("Ingrese una contraseña");
        txtPasswd.setFont(LETRA_TEXTO_2);
        panelUsuario.add(txtPasswd);
        txtPasswd.setBounds(340, 210, 200, 30);

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        panelUsuario.add(btnEntrar);
        btnEntrar.setBounds(600, 210, 110, 40);

        lblCaja.setFont(LETRA_TEXTO_2);
        lblCaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCaja.setText("Caja #*:");
        panelUsuario.add(lblCaja);
        lblCaja.setBounds(150, 250, 180, 30);

        txtCaja.setToolTipText("Ingrese un usuario");
        txtCaja.setFont(LETRA_TEXTO_2);
        panelUsuario.add(txtCaja);
        txtCaja.setBounds(340, 250, 40, 30);

        jLabel1.setFont(LETRA_TEXTO_3);
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("* Campos requeridos");
        panelUsuario.add(jLabel1);
        jLabel1.setBounds(100, 130, 170, 20);

        btnVolver2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolver2MouseClicked(evt);
            }
        });
        panelUsuario.add(btnVolver2);
        btnVolver2.setBounds(30, 20, 50, 50);

        lblVolver.setFont(LETRA_TEXTO_3);
        lblVolver.setText("Volver");
        panelUsuario.add(lblVolver);
        lblVolver.setBounds(90, 30, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        //TODO Arreglar error que se muestra si hay algun campo requerido vacio
        String passwd = new String(txtPasswd.getPassword());
        //if (this.txtUsuario.getText().equals("") || this.txtCaja.getText().equals("") || passwd.equals("")) {
        if (this.txtUsuario.getText().equals("Admin") && String.copyValueOf(this.txtPasswd.getPassword()).equals("123")) {
            new CajaView(txtCaja.getText()).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Usuario o contraseña incorrectos. Por favor intente de nuevo",
                    "Error al iniciar sesión",
                    JOptionPane.ERROR_MESSAGE);
        }
//        } else {
//            JOptionPane.showMessageDialog(this,
//                    "Hay uno o más campos requeridos en blanco.",
//                    "Campos requeridos vacíos",
//                    JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnVolver2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver2MouseClicked
        new ClienteTCP().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolver2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private sacoba.vista.PanelConFondo btnVolver2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCaja;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblVolver;
    private sacoba.vista.PanelConFondo panelTitulo;
    private sacoba.vista.PanelConFondo panelUsuario;
    private sacoba.vista.TransparentTextField txtCaja;
    private sacoba.vista.TransparentPasswordField txtPasswd;
    private sacoba.vista.TransparentTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
