/*
 *  Sistema de Asistencia de Control Bancario
 *  SACOBA
 *  
 *  Marcela Cascante Quiros
 *  Diego Delgado Cerdas
 *  Alejandro Loaiza Arguedas
 *  Jose David Mora Loria
 */
package sacoba.cliente;

import java.awt.event.ActionListener;
import javafx.event.ActionEvent;
import sacoba.cliente.vista.PuertaView;
import sacoba.vista.VentanaBase;

/**
 *
 * @author jmora
 */
public class ClienteTCP extends VentanaBase {

    /**
     * Creates new form ClienteTCP
     */
    public ClienteTCP() {
        initComponents();
        setSize(VentanaBase.ANCHO, VentanaBase.ALTO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new sacoba.vista.PanelConFondo("fondo_panel.png");
        titulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelContenido = new sacoba.vista.PanelConFondo("fondo_panel.png");
        btnClienteCaja = new sacoba.vista.TransparentButton("cajero.png");
        btnClienteMonitor = new sacoba.vista.TransparentButton("monitor.png");
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPuerta = new sacoba.vista.PanelConFondo("puerta.png");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 650));

        titulo1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        titulo1.setText("Sistema de Asistencia de Control Bancario");
        panelTitulo.add(titulo1);
        titulo1.setBounds(20, 10, 480, 30);

        jLabel1.setText("Seleccione el tipo de cliente:");
        panelTitulo.add(jLabel1);
        jLabel1.setBounds(20, 40, 250, 30);

        btnClienteCaja.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnClienteCaja.setMinimumSize(new java.awt.Dimension(200, 200));
        panelContenido.add(btnClienteCaja);
        btnClienteCaja.setBounds(590, 50, 170, 190);

        btnClienteMonitor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnClienteMonitor.setMinimumSize(new java.awt.Dimension(200, 200));
        panelContenido.add(btnClienteMonitor);
        btnClienteMonitor.setBounds(350, 50, 170, 190);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cajero");
        panelContenido.add(jLabel2);
        jLabel2.setBounds(600, 240, 150, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Puerta");
        panelContenido.add(jLabel4);
        jLabel4.setBounds(120, 240, 150, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Monitor");
        panelContenido.add(jLabel5);
        jLabel5.setBounds(360, 240, 150, 30);

        btnPuerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPuertaMouseClicked(evt);
            }
        });
        panelContenido.add(btnPuerta);
        btnPuerta.setBounds(120, 50, 150, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPuertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPuertaMouseClicked
        new PuertaView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPuertaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteTCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteTCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteTCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteTCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteTCP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sacoba.vista.TransparentButton btnClienteCaja;
    private sacoba.vista.TransparentButton btnClienteMonitor;
    private sacoba.vista.PanelConFondo btnPuerta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private sacoba.vista.PanelConFondo panelContenido;
    private sacoba.vista.PanelConFondo panelTitulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
