/*
 *  Sistema de Asistencia de Control Bancario
 *  SACOBA
 *  
 *  Marcela Cascante Quiros
 *  Diego Delgado Cerdas
 *  Alejandro Loaiza Arguedas
 *  Jose David Mora Loria
 */
package sacoba.cliente.vista;

import sacoba.vista.VentanaBase;

/**
 *
 * @author ulacit
 */
public class MonitorView extends VentanaBase {

    /**
     * Creates new form PuertaView
     */
    public MonitorView() {
        initComponents();
        setSize(VentanaBase.ANCHO, VentanaBase.ALTO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConFondo1 = new sacoba.vista.PanelConFondo();
        panelConFondo101 = new sacoba.vista.PanelConFondo();
        panelConFondo102 = new sacoba.vista.PanelConFondo();
        panelConFondo103 = new sacoba.vista.PanelConFondo();
        panelConFondo104 = new sacoba.vista.PanelConFondo();
        panelConFondo105 = new sacoba.vista.PanelConFondo();
        panelConFondo106 = new sacoba.vista.PanelConFondo();
        panelConFondo107 = new sacoba.vista.PanelConFondo();
        panelConFondo108 = new sacoba.vista.PanelConFondo();
        panelConFondo109 = new sacoba.vista.PanelConFondo();
        panelConFondo110 = new sacoba.vista.PanelConFondo();
        panelConFondo111 = new sacoba.vista.PanelConFondo();
        panelConFondo112 = new sacoba.vista.PanelConFondo();
        panelConFondo113 = new sacoba.vista.PanelConFondo();
        panelConFondo114 = new sacoba.vista.PanelConFondo();
        panelConFondo115 = new sacoba.vista.PanelConFondo();
        panelConFondo116 = new sacoba.vista.PanelConFondo();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBienvenidos = new sacoba.vista.TransparentTextArea();
        panelClientes = new sacoba.vista.PanelConFondo("fondo_panel.png");
        lblTituloCuentas = new javax.swing.JLabel();
        lblTituloPlataforma = new javax.swing.JLabel();
        lblTituloTramites = new javax.swing.JLabel();
        lblPlataforma1 = new javax.swing.JLabel();
        lblPlataforma3 = new javax.swing.JLabel();
        lblPlataforma4 = new javax.swing.JLabel();
        panelConFondo2 = new sacoba.vista.PanelConFondo();
        panelConFondo3 = new sacoba.vista.PanelConFondo();
        panelConFondo4 = new sacoba.vista.PanelConFondo();
        panelConFondo5 = new sacoba.vista.PanelConFondo("account-balance-blanco.png");
        panelConFondo6 = new sacoba.vista.PanelConFondo();
        panelConFondo7 = new sacoba.vista.PanelConFondo();
        panelConFondo8 = new sacoba.vista.PanelConFondo();
        panelConFondo9 = new sacoba.vista.PanelConFondo();
        panelConFondo10 = new sacoba.vista.PanelConFondo();
        panelConFondo11 = new sacoba.vista.PanelConFondo();
        panelConFondo12 = new sacoba.vista.PanelConFondo();
        panelConFondo21 = new sacoba.vista.PanelConFondo();
        panelConFondo22 = new sacoba.vista.PanelConFondo();
        panelConFondo23 = new sacoba.vista.PanelConFondo();
        panelConFondo24 = new sacoba.vista.PanelConFondo();
        panelConFondo25 = new sacoba.vista.PanelConFondo();
        panelConFondo26 = new sacoba.vista.PanelConFondo();
        panelConFondo27 = new sacoba.vista.PanelConFondo();
        panelConFondo28 = new sacoba.vista.PanelConFondo();
        panelConFondo29 = new sacoba.vista.PanelConFondo();
        panelConFondo30 = new sacoba.vista.PanelConFondo();
        panelConFondo31 = new sacoba.vista.PanelConFondo();
        panelConFondo32 = new sacoba.vista.PanelConFondo();
        panelConFondo33 = new sacoba.vista.PanelConFondo();
        panelConFondo34 = new sacoba.vista.PanelConFondo();
        panelConFondo35 = new sacoba.vista.PanelConFondo();
        panelConFondo36 = new sacoba.vista.PanelConFondo();
        panelConFondo37 = new sacoba.vista.PanelConFondo();
        panelConFondo38 = new sacoba.vista.PanelConFondo();
        panelConFondo39 = new sacoba.vista.PanelConFondo();
        panelConFondo40 = new sacoba.vista.PanelConFondo();
        panelConFondo41 = new sacoba.vista.PanelConFondo();
        panelConFondo42 = new sacoba.vista.PanelConFondo();
        panelConFondo43 = new sacoba.vista.PanelConFondo();
        panelConFondo44 = new sacoba.vista.PanelConFondo();
        panelConFondo45 = new sacoba.vista.PanelConFondo();
        panelConFondo46 = new sacoba.vista.PanelConFondo();
        panelConFondo47 = new sacoba.vista.PanelConFondo();
        panelConFondo48 = new sacoba.vista.PanelConFondo();
        panelConFondo49 = new sacoba.vista.PanelConFondo();
        panelConFondo50 = new sacoba.vista.PanelConFondo();
        panelConFondo51 = new sacoba.vista.PanelConFondo();
        panelConFondo52 = new sacoba.vista.PanelConFondo();
        panelConFondo53 = new sacoba.vista.PanelConFondo();
        panelConFondo54 = new sacoba.vista.PanelConFondo();
        panelConFondo55 = new sacoba.vista.PanelConFondo();
        panelConFondo56 = new sacoba.vista.PanelConFondo();
        panelConFondo57 = new sacoba.vista.PanelConFondo();
        panelConFondo58 = new sacoba.vista.PanelConFondo();
        panelConFondo59 = new sacoba.vista.PanelConFondo();
        panelConFondo60 = new sacoba.vista.PanelConFondo();
        panelConFondo61 = new sacoba.vista.PanelConFondo();
        panelConFondo62 = new sacoba.vista.PanelConFondo();
        panelConFondo63 = new sacoba.vista.PanelConFondo();
        panelConFondo64 = new sacoba.vista.PanelConFondo();
        panelConFondo65 = new sacoba.vista.PanelConFondo();
        panelConFondo66 = new sacoba.vista.PanelConFondo();
        panelConFondo67 = new sacoba.vista.PanelConFondo();
        panelConFondo68 = new sacoba.vista.PanelConFondo();
        panelConFondo69 = new sacoba.vista.PanelConFondo();
        panelConFondo70 = new sacoba.vista.PanelConFondo();
        panelConFondo71 = new sacoba.vista.PanelConFondo();
        panelConFondo72 = new sacoba.vista.PanelConFondo();
        panelConFondo73 = new sacoba.vista.PanelConFondo();
        panelConFondo74 = new sacoba.vista.PanelConFondo();
        panelConFondo75 = new sacoba.vista.PanelConFondo();
        panelConFondo76 = new sacoba.vista.PanelConFondo();
        panelConFondo85 = new sacoba.vista.PanelConFondo();
        panelConFondo86 = new sacoba.vista.PanelConFondo();
        panelConFondo87 = new sacoba.vista.PanelConFondo();
        panelConFondo88 = new sacoba.vista.PanelConFondo();
        panelConFondo89 = new sacoba.vista.PanelConFondo();
        panelConFondo90 = new sacoba.vista.PanelConFondo();
        panelConFondo91 = new sacoba.vista.PanelConFondo();
        panelConFondo92 = new sacoba.vista.PanelConFondo();
        panelConFondo93 = new sacoba.vista.PanelConFondo();
        panelConFondo94 = new sacoba.vista.PanelConFondo();
        panelConFondo95 = new sacoba.vista.PanelConFondo();
        panelConFondo96 = new sacoba.vista.PanelConFondo();
        panelConFondo97 = new sacoba.vista.PanelConFondo();
        panelConFondo98 = new sacoba.vista.PanelConFondo();
        panelConFondo99 = new sacoba.vista.PanelConFondo();
        panelConFondo100 = new sacoba.vista.PanelConFondo();
        panelConFondo133 = new sacoba.vista.PanelConFondo();
        panelConFondo134 = new sacoba.vista.PanelConFondo();
        panelConFondo135 = new sacoba.vista.PanelConFondo();
        panelConFondo136 = new sacoba.vista.PanelConFondo();
        panelConFondo137 = new sacoba.vista.PanelConFondo();
        panelConFondo138 = new sacoba.vista.PanelConFondo();
        panelConFondo139 = new sacoba.vista.PanelConFondo();
        panelConFondo140 = new sacoba.vista.PanelConFondo();
        panelConFondo141 = new sacoba.vista.PanelConFondo();
        panelConFondo142 = new sacoba.vista.PanelConFondo();
        panelConFondo143 = new sacoba.vista.PanelConFondo();
        panelConFondo144 = new sacoba.vista.PanelConFondo();
        panelConFondo145 = new sacoba.vista.PanelConFondo();
        panelConFondo146 = new sacoba.vista.PanelConFondo();
        panelConFondo147 = new sacoba.vista.PanelConFondo();
        panelConFondo148 = new sacoba.vista.PanelConFondo();
        panelConFondo149 = new sacoba.vista.PanelConFondo();
        panelConFondo150 = new sacoba.vista.PanelConFondo();
        panelConFondo151 = new sacoba.vista.PanelConFondo();
        panelConFondo152 = new sacoba.vista.PanelConFondo();
        panelConFondo153 = new sacoba.vista.PanelConFondo();
        panelConFondo154 = new sacoba.vista.PanelConFondo();
        panelConFondo155 = new sacoba.vista.PanelConFondo();
        panelConFondo156 = new sacoba.vista.PanelConFondo();
        panelConFondo157 = new sacoba.vista.PanelConFondo();
        panelConFondo158 = new sacoba.vista.PanelConFondo();
        panelConFondo159 = new sacoba.vista.PanelConFondo();
        panelConFondo160 = new sacoba.vista.PanelConFondo();
        panelConFondo161 = new sacoba.vista.PanelConFondo();
        panelConFondo162 = new sacoba.vista.PanelConFondo();
        panelConFondo163 = new sacoba.vista.PanelConFondo();
        panelConFondo164 = new sacoba.vista.PanelConFondo();
        panelConFondo165 = new sacoba.vista.PanelConFondo();
        panelConFondo166 = new sacoba.vista.PanelConFondo();
        panelConFondo167 = new sacoba.vista.PanelConFondo();
        panelConFondo168 = new sacoba.vista.PanelConFondo();
        panelConFondo169 = new sacoba.vista.PanelConFondo();
        panelConFondo170 = new sacoba.vista.PanelConFondo();
        panelConFondo171 = new sacoba.vista.PanelConFondo();
        panelConFondo172 = new sacoba.vista.PanelConFondo();
        panelConFondo173 = new sacoba.vista.PanelConFondo();
        panelConFondo174 = new sacoba.vista.PanelConFondo();
        panelConFondo175 = new sacoba.vista.PanelConFondo();
        panelConFondo176 = new sacoba.vista.PanelConFondo();
        panelConFondo177 = new sacoba.vista.PanelConFondo();
        panelConFondo178 = new sacoba.vista.PanelConFondo();
        panelConFondo179 = new sacoba.vista.PanelConFondo();
        panelConFondo180 = new sacoba.vista.PanelConFondo();
        panelConFondo181 = new sacoba.vista.PanelConFondo();
        panelConFondo182 = new sacoba.vista.PanelConFondo();
        panelConFondo183 = new sacoba.vista.PanelConFondo();
        panelConFondo184 = new sacoba.vista.PanelConFondo();
        panelConFondo185 = new sacoba.vista.PanelConFondo();
        panelConFondo186 = new sacoba.vista.PanelConFondo();
        panelConFondo187 = new sacoba.vista.PanelConFondo();
        panelConFondo188 = new sacoba.vista.PanelConFondo();
        panelConFondo189 = new sacoba.vista.PanelConFondo();
        panelConFondo190 = new sacoba.vista.PanelConFondo();
        panelConFondo191 = new sacoba.vista.PanelConFondo();
        panelConFondo192 = new sacoba.vista.PanelConFondo();
        panelConFondo193 = new sacoba.vista.PanelConFondo();
        panelConFondo194 = new sacoba.vista.PanelConFondo();
        panelConFondo195 = new sacoba.vista.PanelConFondo();
        panelConFondo196 = new sacoba.vista.PanelConFondo();
        panelConFondo197 = new sacoba.vista.PanelConFondo();
        panelConFondo198 = new sacoba.vista.PanelConFondo();
        panelConFondo199 = new sacoba.vista.PanelConFondo();
        panelConFondo200 = new sacoba.vista.PanelConFondo();
        panelConFondo201 = new sacoba.vista.PanelConFondo();
        panelConFondo202 = new sacoba.vista.PanelConFondo();
        panelConFondo203 = new sacoba.vista.PanelConFondo();
        panelConFondo204 = new sacoba.vista.PanelConFondo();
        panelConFondo205 = new sacoba.vista.PanelConFondo();
        panelConFondo206 = new sacoba.vista.PanelConFondo();
        panelConFondo207 = new sacoba.vista.PanelConFondo();
        panelConFondo208 = new sacoba.vista.PanelConFondo();
        panelConFondo209 = new sacoba.vista.PanelConFondo();
        panelConFondo210 = new sacoba.vista.PanelConFondo();
        panelConFondo211 = new sacoba.vista.PanelConFondo();
        panelConFondo212 = new sacoba.vista.PanelConFondo();
        panelConFondo213 = new sacoba.vista.PanelConFondo();
        panelConFondo214 = new sacoba.vista.PanelConFondo();
        panelConFondo215 = new sacoba.vista.PanelConFondo();
        panelConFondo216 = new sacoba.vista.PanelConFondo();
        panelConFondo217 = new sacoba.vista.PanelConFondo();
        panelConFondo218 = new sacoba.vista.PanelConFondo();
        panelConFondo219 = new sacoba.vista.PanelConFondo();
        panelConFondo220 = new sacoba.vista.PanelConFondo();
        panelConFondo221 = new sacoba.vista.PanelConFondo();
        panelConFondo222 = new sacoba.vista.PanelConFondo();
        panelConFondo223 = new sacoba.vista.PanelConFondo();
        panelConFondo224 = new sacoba.vista.PanelConFondo();
        panelConFondo225 = new sacoba.vista.PanelConFondo();
        panelConFondo226 = new sacoba.vista.PanelConFondo();
        panelConFondo227 = new sacoba.vista.PanelConFondo();
        panelConFondo228 = new sacoba.vista.PanelConFondo();
        panelConFondo229 = new sacoba.vista.PanelConFondo();
        panelConFondo230 = new sacoba.vista.PanelConFondo();
        panelConFondo231 = new sacoba.vista.PanelConFondo();
        panelConFondo232 = new sacoba.vista.PanelConFondo();
        panelConFondo233 = new sacoba.vista.PanelConFondo();
        panelConFondo234 = new sacoba.vista.PanelConFondo();
        panelConFondo235 = new sacoba.vista.PanelConFondo();
        panelConFondo236 = new sacoba.vista.PanelConFondo();
        panelConFondo237 = new sacoba.vista.PanelConFondo();
        panelConFondo238 = new sacoba.vista.PanelConFondo();
        panelConFondo239 = new sacoba.vista.PanelConFondo();
        panelConFondo240 = new sacoba.vista.PanelConFondo();
        panelConFondo241 = new sacoba.vista.PanelConFondo();
        panelConFondo242 = new sacoba.vista.PanelConFondo();
        panelConFondo243 = new sacoba.vista.PanelConFondo();
        panelConFondo244 = new sacoba.vista.PanelConFondo();
        panelConFondo245 = new sacoba.vista.PanelConFondo();
        panelConFondo246 = new sacoba.vista.PanelConFondo();
        panelConFondo247 = new sacoba.vista.PanelConFondo();
        panelConFondo248 = new sacoba.vista.PanelConFondo();
        panelConFondo249 = new sacoba.vista.PanelConFondo();
        panelConFondo250 = new sacoba.vista.PanelConFondo();
        panelConFondo251 = new sacoba.vista.PanelConFondo();
        panelConFondo252 = new sacoba.vista.PanelConFondo();
        panelConFondo253 = new sacoba.vista.PanelConFondo();
        panelConFondo254 = new sacoba.vista.PanelConFondo();
        panelConFondo255 = new sacoba.vista.PanelConFondo();
        panelConFondo256 = new sacoba.vista.PanelConFondo();
        panelConFondo257 = new sacoba.vista.PanelConFondo();
        panelConFondo258 = new sacoba.vista.PanelConFondo();
        panelConFondo259 = new sacoba.vista.PanelConFondo();
        panelConFondo260 = new sacoba.vista.PanelConFondo();
        panelConFondo261 = new sacoba.vista.PanelConFondo();
        panelConFondo262 = new sacoba.vista.PanelConFondo();
        panelConFondo263 = new sacoba.vista.PanelConFondo();
        panelConFondo264 = new sacoba.vista.PanelConFondo();
        panelConFondo265 = new sacoba.vista.PanelConFondo();
        panelConFondo266 = new sacoba.vista.PanelConFondo();
        panelConFondo267 = new sacoba.vista.PanelConFondo();
        panelConFondo268 = new sacoba.vista.PanelConFondo();
        panelConFondo269 = new sacoba.vista.PanelConFondo();
        panelConFondo270 = new sacoba.vista.PanelConFondo();
        panelConFondo271 = new sacoba.vista.PanelConFondo();
        panelConFondo272 = new sacoba.vista.PanelConFondo();
        panelConFondo273 = new sacoba.vista.PanelConFondo();
        panelConFondo274 = new sacoba.vista.PanelConFondo();
        panelConFondo275 = new sacoba.vista.PanelConFondo();
        panelConFondo276 = new sacoba.vista.PanelConFondo();
        panelConFondo277 = new sacoba.vista.PanelConFondo();
        panelConFondo278 = new sacoba.vista.PanelConFondo();
        panelConFondo279 = new sacoba.vista.PanelConFondo();
        panelConFondo280 = new sacoba.vista.PanelConFondo();
        panelConFondo281 = new sacoba.vista.PanelConFondo();
        panelConFondo282 = new sacoba.vista.PanelConFondo();
        panelConFondo283 = new sacoba.vista.PanelConFondo();
        panelConFondo284 = new sacoba.vista.PanelConFondo();
        panelConFondo285 = new sacoba.vista.PanelConFondo();
        panelConFondo286 = new sacoba.vista.PanelConFondo();
        panelConFondo287 = new sacoba.vista.PanelConFondo();
        panelConFondo288 = new sacoba.vista.PanelConFondo();
        panelConFondo289 = new sacoba.vista.PanelConFondo();
        panelConFondo290 = new sacoba.vista.PanelConFondo();
        panelConFondo291 = new sacoba.vista.PanelConFondo();
        panelConFondo292 = new sacoba.vista.PanelConFondo();
        panelConFondo293 = new sacoba.vista.PanelConFondo();
        panelConFondo294 = new sacoba.vista.PanelConFondo();
        panelConFondo295 = new sacoba.vista.PanelConFondo();
        panelConFondo296 = new sacoba.vista.PanelConFondo();
        panelConFondo297 = new sacoba.vista.PanelConFondo();
        panelConFondo298 = new sacoba.vista.PanelConFondo();
        panelConFondo299 = new sacoba.vista.PanelConFondo();
        panelConFondo300 = new sacoba.vista.PanelConFondo();
        panelConFondo301 = new sacoba.vista.PanelConFondo();
        panelConFondo302 = new sacoba.vista.PanelConFondo();
        panelConFondo303 = new sacoba.vista.PanelConFondo();
        panelConFondo304 = new sacoba.vista.PanelConFondo();
        panelConFondo305 = new sacoba.vista.PanelConFondo();
        panelConFondo306 = new sacoba.vista.PanelConFondo();
        panelConFondo307 = new sacoba.vista.PanelConFondo();
        panelConFondo308 = new sacoba.vista.PanelConFondo();
        panelConFondo309 = new sacoba.vista.PanelConFondo();
        panelConFondo310 = new sacoba.vista.PanelConFondo();
        panelConFondo311 = new sacoba.vista.PanelConFondo();
        panelConFondo312 = new sacoba.vista.PanelConFondo();
        panelConFondo313 = new sacoba.vista.PanelConFondo();
        panelConFondo314 = new sacoba.vista.PanelConFondo();
        panelConFondo315 = new sacoba.vista.PanelConFondo();
        panelConFondo316 = new sacoba.vista.PanelConFondo();
        panelConFondo317 = new sacoba.vista.PanelConFondo();
        panelConFondo318 = new sacoba.vista.PanelConFondo();
        panelConFondo319 = new sacoba.vista.PanelConFondo();
        panelConFondo320 = new sacoba.vista.PanelConFondo();
        panelConFondo321 = new sacoba.vista.PanelConFondo();
        panelConFondo322 = new sacoba.vista.PanelConFondo();
        panelConFondo323 = new sacoba.vista.PanelConFondo();
        panelConFondo324 = new sacoba.vista.PanelConFondo();
        panelConFondo325 = new sacoba.vista.PanelConFondo();
        panelConFondo326 = new sacoba.vista.PanelConFondo();
        panelConFondo327 = new sacoba.vista.PanelConFondo();
        panelConFondo328 = new sacoba.vista.PanelConFondo();
        panelConFondo329 = new sacoba.vista.PanelConFondo();
        panelConFondo330 = new sacoba.vista.PanelConFondo();
        panelConFondo331 = new sacoba.vista.PanelConFondo();
        panelConFondo332 = new sacoba.vista.PanelConFondo();
        panelConFondo333 = new sacoba.vista.PanelConFondo();
        panelConFondo334 = new sacoba.vista.PanelConFondo();
        panelConFondo335 = new sacoba.vista.PanelConFondo();
        panelConFondo336 = new sacoba.vista.PanelConFondo();
        panelConFondo337 = new sacoba.vista.PanelConFondo();
        panelConFondo338 = new sacoba.vista.PanelConFondo();
        panelConFondo339 = new sacoba.vista.PanelConFondo();
        panelConFondo340 = new sacoba.vista.PanelConFondo();
        panelConFondo341 = new sacoba.vista.PanelConFondo();
        panelConFondo342 = new sacoba.vista.PanelConFondo();
        panelConFondo343 = new sacoba.vista.PanelConFondo();
        panelConFondo344 = new sacoba.vista.PanelConFondo();
        panelConFondo345 = new sacoba.vista.PanelConFondo();
        panelConFondo346 = new sacoba.vista.PanelConFondo();
        panelConFondo347 = new sacoba.vista.PanelConFondo();
        panelConFondo348 = new sacoba.vista.PanelConFondo();
        panelConFondo349 = new sacoba.vista.PanelConFondo();
        panelConFondo350 = new sacoba.vista.PanelConFondo();
        panelConFondo351 = new sacoba.vista.PanelConFondo();
        panelConFondo352 = new sacoba.vista.PanelConFondo();
        panelConFondo353 = new sacoba.vista.PanelConFondo();
        panelConFondo354 = new sacoba.vista.PanelConFondo();
        panelConFondo355 = new sacoba.vista.PanelConFondo();
        panelConFondo356 = new sacoba.vista.PanelConFondo();
        panelConFondo357 = new sacoba.vista.PanelConFondo();
        panelConFondo358 = new sacoba.vista.PanelConFondo();
        panelConFondo359 = new sacoba.vista.PanelConFondo();
        panelConFondo360 = new sacoba.vista.PanelConFondo();
        panelConFondo361 = new sacoba.vista.PanelConFondo();
        panelConFondo362 = new sacoba.vista.PanelConFondo();
        panelConFondo363 = new sacoba.vista.PanelConFondo();
        panelConFondo364 = new sacoba.vista.PanelConFondo();
        panelConFondo365 = new sacoba.vista.PanelConFondo();
        panelConFondo366 = new sacoba.vista.PanelConFondo();
        panelConFondo367 = new sacoba.vista.PanelConFondo();
        panelConFondo368 = new sacoba.vista.PanelConFondo();
        panelConFondo369 = new sacoba.vista.PanelConFondo();
        panelConFondo370 = new sacoba.vista.PanelConFondo();
        panelConFondo371 = new sacoba.vista.PanelConFondo();
        panelConFondo372 = new sacoba.vista.PanelConFondo();
        panelConFondo13 = new sacoba.vista.PanelConFondo("tramite_blanco.png");
        panelConFondo14 = new sacoba.vista.PanelConFondo();
        panelConFondo15 = new sacoba.vista.PanelConFondo();
        panelConFondo16 = new sacoba.vista.PanelConFondo();
        panelConFondo17 = new sacoba.vista.PanelConFondo();
        panelConFondo18 = new sacoba.vista.PanelConFondo();
        panelConFondo19 = new sacoba.vista.PanelConFondo();
        panelConFondo20 = new sacoba.vista.PanelConFondo();
        panelConFondo77 = new sacoba.vista.PanelConFondo();
        panelConFondo78 = new sacoba.vista.PanelConFondo();
        panelConFondo79 = new sacoba.vista.PanelConFondo();
        panelConFondo80 = new sacoba.vista.PanelConFondo();
        panelConFondo81 = new sacoba.vista.PanelConFondo();
        panelConFondo82 = new sacoba.vista.PanelConFondo();
        panelConFondo83 = new sacoba.vista.PanelConFondo();
        panelConFondo84 = new sacoba.vista.PanelConFondo();
        panelConFondo117 = new sacoba.vista.PanelConFondo();
        panelConFondo118 = new sacoba.vista.PanelConFondo();
        panelConFondo119 = new sacoba.vista.PanelConFondo();
        panelConFondo120 = new sacoba.vista.PanelConFondo();
        panelConFondo121 = new sacoba.vista.PanelConFondo();
        panelConFondo122 = new sacoba.vista.PanelConFondo();
        panelConFondo123 = new sacoba.vista.PanelConFondo();
        panelConFondo124 = new sacoba.vista.PanelConFondo();
        panelConFondo125 = new sacoba.vista.PanelConFondo();
        panelConFondo126 = new sacoba.vista.PanelConFondo();
        panelConFondo127 = new sacoba.vista.PanelConFondo();
        panelConFondo128 = new sacoba.vista.PanelConFondo();
        panelConFondo129 = new sacoba.vista.PanelConFondo();
        panelConFondo130 = new sacoba.vista.PanelConFondo();
        panelConFondo131 = new sacoba.vista.PanelConFondo();
        panelConFondo132 = new sacoba.vista.PanelConFondo();
        panelConFondo373 = new sacoba.vista.PanelConFondo();
        panelConFondo374 = new sacoba.vista.PanelConFondo();
        panelConFondo375 = new sacoba.vista.PanelConFondo();
        panelConFondo376 = new sacoba.vista.PanelConFondo();
        panelConFondo377 = new sacoba.vista.PanelConFondo();
        panelConFondo378 = new sacoba.vista.PanelConFondo();
        panelConFondo379 = new sacoba.vista.PanelConFondo();
        panelConFondo380 = new sacoba.vista.PanelConFondo();
        panelConFondo381 = new sacoba.vista.PanelConFondo();
        panelConFondo382 = new sacoba.vista.PanelConFondo();
        panelConFondo383 = new sacoba.vista.PanelConFondo();
        panelConFondo384 = new sacoba.vista.PanelConFondo();
        panelConFondo385 = new sacoba.vista.PanelConFondo();
        panelConFondo386 = new sacoba.vista.PanelConFondo();
        panelConFondo387 = new sacoba.vista.PanelConFondo();
        panelConFondo388 = new sacoba.vista.PanelConFondo();
        panelConFondo389 = new sacoba.vista.PanelConFondo();
        panelConFondo390 = new sacoba.vista.PanelConFondo();
        panelConFondo391 = new sacoba.vista.PanelConFondo();
        panelConFondo392 = new sacoba.vista.PanelConFondo();
        panelConFondo393 = new sacoba.vista.PanelConFondo();
        panelConFondo394 = new sacoba.vista.PanelConFondo();
        panelConFondo395 = new sacoba.vista.PanelConFondo();
        panelConFondo396 = new sacoba.vista.PanelConFondo();
        panelConFondo397 = new sacoba.vista.PanelConFondo();
        panelConFondo398 = new sacoba.vista.PanelConFondo();
        panelConFondo399 = new sacoba.vista.PanelConFondo();
        panelConFondo400 = new sacoba.vista.PanelConFondo();
        panelConFondo401 = new sacoba.vista.PanelConFondo();
        panelConFondo402 = new sacoba.vista.PanelConFondo();
        panelConFondo403 = new sacoba.vista.PanelConFondo();
        panelConFondo404 = new sacoba.vista.PanelConFondo();
        panelConFondo405 = new sacoba.vista.PanelConFondo("group_blanco.png");
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSigue = new sacoba.vista.TransparentTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        transparentTextArea1 = new sacoba.vista.TransparentTextArea();

        panelConFondo101.add(panelConFondo102);
        panelConFondo102.setBounds(90, 300, 110, 100);

        panelConFondo103.add(panelConFondo104);
        panelConFondo104.setBounds(90, 300, 110, 100);

        panelConFondo101.add(panelConFondo103);
        panelConFondo103.setBounds(90, 150, 110, 100);

        panelConFondo105.add(panelConFondo106);
        panelConFondo106.setBounds(90, 300, 110, 100);

        panelConFondo107.add(panelConFondo108);
        panelConFondo108.setBounds(90, 300, 110, 100);

        panelConFondo105.add(panelConFondo107);
        panelConFondo107.setBounds(90, 150, 110, 100);

        panelConFondo101.add(panelConFondo105);
        panelConFondo105.setBounds(90, 150, 110, 100);

        panelConFondo109.add(panelConFondo110);
        panelConFondo110.setBounds(90, 300, 110, 100);

        panelConFondo111.add(panelConFondo112);
        panelConFondo112.setBounds(90, 300, 110, 100);

        panelConFondo109.add(panelConFondo111);
        panelConFondo111.setBounds(90, 150, 110, 100);

        panelConFondo113.add(panelConFondo114);
        panelConFondo114.setBounds(90, 300, 110, 100);

        panelConFondo115.add(panelConFondo116);
        panelConFondo116.setBounds(90, 300, 110, 100);

        panelConFondo113.add(panelConFondo115);
        panelConFondo115.setBounds(90, 150, 110, 100);

        panelConFondo109.add(panelConFondo113);
        panelConFondo113.setBounds(90, 150, 110, 100);

        panelConFondo101.add(panelConFondo109);
        panelConFondo109.setBounds(90, 150, 110, 100);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 650));
        setSize(new java.awt.Dimension(950, 650));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtBienvenidos.setEditable(false);
        txtBienvenidos.setColumns(20);
        txtBienvenidos.setRows(5);
        txtBienvenidos.setText("¡Bienvenido, pronto le atenderemos!");
        txtBienvenidos.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jScrollPane1.setViewportView(txtBienvenidos);
        txtBienvenidos.getAccessibleContext().setAccessibleName("");
        txtBienvenidos.getAccessibleContext().setAccessibleDescription("");
        txtBienvenidos.getAccessibleContext().setAccessibleParent(txtBienvenidos);

        panelClientes.setEnabled(false);

        lblTituloCuentas.setFont(LETRA_TEXTO_1);
        lblTituloCuentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloCuentas.setText("Cuentas:");
        lblTituloCuentas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelClientes.add(lblTituloCuentas);
        lblTituloCuentas.setBounds(120, 420, 50, 30);

        lblTituloPlataforma.setFont(LETRA_TEXTO_1);
        lblTituloPlataforma.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloPlataforma.setText("Plataforma:");
        lblTituloPlataforma.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelClientes.add(lblTituloPlataforma);
        lblTituloPlataforma.setBounds(110, 120, 70, 30);

        lblTituloTramites.setFont(LETRA_TEXTO_1);
        lblTituloTramites.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloTramites.setText("Trámites:");
        lblTituloTramites.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelClientes.add(lblTituloTramites);
        lblTituloTramites.setBounds(120, 270, 50, 30);

        lblPlataforma1.setFont(LETRA_TITULO);
        lblPlataforma1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlataforma1.setText("0");
        lblPlataforma1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelClientes.add(lblPlataforma1);
        lblPlataforma1.setBounds(110, 440, 60, 40);

        lblPlataforma3.setFont(LETRA_TITULO);
        lblPlataforma3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlataforma3.setText("0");
        lblPlataforma3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelClientes.add(lblPlataforma3);
        lblPlataforma3.setBounds(110, 130, 60, 40);

        lblPlataforma4.setFont(LETRA_TITULO);
        lblPlataforma4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlataforma4.setText("0");
        lblPlataforma4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelClientes.add(lblPlataforma4);
        lblPlataforma4.setBounds(110, 280, 60, 40);
        panelClientes.add(panelConFondo2);
        panelConFondo2.setBounds(90, 300, 100, 100);
        panelClientes.add(panelConFondo3);
        panelConFondo3.setBounds(90, 298, 120, 100);
        panelClientes.add(panelConFondo4);
        panelConFondo4.setBounds(90, 300, 100, 100);

        panelConFondo5.add(panelConFondo6);
        panelConFondo6.setBounds(90, 300, 110, 100);

        panelConFondo7.add(panelConFondo8);
        panelConFondo8.setBounds(90, 300, 110, 100);

        panelConFondo5.add(panelConFondo7);
        panelConFondo7.setBounds(90, 150, 110, 100);

        panelConFondo9.add(panelConFondo10);
        panelConFondo10.setBounds(90, 300, 110, 100);

        panelConFondo11.add(panelConFondo12);
        panelConFondo12.setBounds(90, 300, 110, 100);

        panelConFondo9.add(panelConFondo11);
        panelConFondo11.setBounds(90, 150, 110, 100);

        panelConFondo5.add(panelConFondo9);
        panelConFondo9.setBounds(90, 150, 110, 100);

        panelConFondo21.add(panelConFondo22);
        panelConFondo22.setBounds(90, 300, 110, 100);

        panelConFondo23.add(panelConFondo24);
        panelConFondo24.setBounds(90, 300, 110, 100);

        panelConFondo21.add(panelConFondo23);
        panelConFondo23.setBounds(90, 150, 110, 100);

        panelConFondo25.add(panelConFondo26);
        panelConFondo26.setBounds(90, 300, 110, 100);

        panelConFondo27.add(panelConFondo28);
        panelConFondo28.setBounds(90, 300, 110, 100);

        panelConFondo25.add(panelConFondo27);
        panelConFondo27.setBounds(90, 150, 110, 100);

        panelConFondo21.add(panelConFondo25);
        panelConFondo25.setBounds(90, 150, 110, 100);

        panelConFondo29.add(panelConFondo30);
        panelConFondo30.setBounds(90, 300, 110, 100);

        panelConFondo31.add(panelConFondo32);
        panelConFondo32.setBounds(90, 300, 110, 100);

        panelConFondo29.add(panelConFondo31);
        panelConFondo31.setBounds(90, 150, 110, 100);

        panelConFondo33.add(panelConFondo34);
        panelConFondo34.setBounds(90, 300, 110, 100);

        panelConFondo35.add(panelConFondo36);
        panelConFondo36.setBounds(90, 300, 110, 100);

        panelConFondo33.add(panelConFondo35);
        panelConFondo35.setBounds(90, 150, 110, 100);

        panelConFondo29.add(panelConFondo33);
        panelConFondo33.setBounds(90, 150, 110, 100);

        panelConFondo37.add(panelConFondo38);
        panelConFondo38.setBounds(90, 300, 110, 100);

        panelConFondo39.add(panelConFondo40);
        panelConFondo40.setBounds(90, 300, 110, 100);

        panelConFondo37.add(panelConFondo39);
        panelConFondo39.setBounds(90, 150, 110, 100);

        panelConFondo41.add(panelConFondo42);
        panelConFondo42.setBounds(90, 300, 110, 100);

        panelConFondo43.add(panelConFondo44);
        panelConFondo44.setBounds(90, 300, 110, 100);

        panelConFondo41.add(panelConFondo43);
        panelConFondo43.setBounds(90, 150, 110, 100);

        panelConFondo37.add(panelConFondo41);
        panelConFondo41.setBounds(90, 150, 110, 100);

        panelConFondo29.add(panelConFondo37);
        panelConFondo37.setBounds(90, 300, 110, 100);

        panelConFondo21.add(panelConFondo29);
        panelConFondo29.setBounds(90, 300, 110, 100);

        panelConFondo5.add(panelConFondo21);
        panelConFondo21.setBounds(90, 300, 110, 100);

        panelConFondo45.add(panelConFondo46);
        panelConFondo46.setBounds(90, 300, 110, 100);

        panelConFondo47.add(panelConFondo48);
        panelConFondo48.setBounds(90, 300, 110, 100);

        panelConFondo45.add(panelConFondo47);
        panelConFondo47.setBounds(90, 150, 110, 100);

        panelConFondo49.add(panelConFondo50);
        panelConFondo50.setBounds(90, 300, 110, 100);

        panelConFondo51.add(panelConFondo52);
        panelConFondo52.setBounds(90, 300, 110, 100);

        panelConFondo49.add(panelConFondo51);
        panelConFondo51.setBounds(90, 150, 110, 100);

        panelConFondo45.add(panelConFondo49);
        panelConFondo49.setBounds(90, 150, 110, 100);

        panelConFondo53.add(panelConFondo54);
        panelConFondo54.setBounds(90, 300, 110, 100);

        panelConFondo55.add(panelConFondo56);
        panelConFondo56.setBounds(90, 300, 110, 100);

        panelConFondo53.add(panelConFondo55);
        panelConFondo55.setBounds(90, 150, 110, 100);

        panelConFondo57.add(panelConFondo58);
        panelConFondo58.setBounds(90, 300, 110, 100);

        panelConFondo59.add(panelConFondo60);
        panelConFondo60.setBounds(90, 300, 110, 100);

        panelConFondo57.add(panelConFondo59);
        panelConFondo59.setBounds(90, 150, 110, 100);

        panelConFondo53.add(panelConFondo57);
        panelConFondo57.setBounds(90, 150, 110, 100);

        panelConFondo61.add(panelConFondo62);
        panelConFondo62.setBounds(90, 300, 110, 100);

        panelConFondo63.add(panelConFondo64);
        panelConFondo64.setBounds(90, 300, 110, 100);

        panelConFondo61.add(panelConFondo63);
        panelConFondo63.setBounds(90, 150, 110, 100);

        panelConFondo65.add(panelConFondo66);
        panelConFondo66.setBounds(90, 300, 110, 100);

        panelConFondo67.add(panelConFondo68);
        panelConFondo68.setBounds(90, 300, 110, 100);

        panelConFondo65.add(panelConFondo67);
        panelConFondo67.setBounds(90, 150, 110, 100);

        panelConFondo61.add(panelConFondo65);
        panelConFondo65.setBounds(90, 150, 110, 100);

        panelConFondo69.add(panelConFondo70);
        panelConFondo70.setBounds(90, 300, 110, 100);

        panelConFondo71.add(panelConFondo72);
        panelConFondo72.setBounds(90, 300, 110, 100);

        panelConFondo69.add(panelConFondo71);
        panelConFondo71.setBounds(90, 150, 110, 100);

        panelConFondo73.add(panelConFondo74);
        panelConFondo74.setBounds(90, 300, 110, 100);

        panelConFondo75.add(panelConFondo76);
        panelConFondo76.setBounds(90, 300, 110, 100);

        panelConFondo73.add(panelConFondo75);
        panelConFondo75.setBounds(90, 150, 110, 100);

        panelConFondo69.add(panelConFondo73);
        panelConFondo73.setBounds(90, 150, 110, 100);

        panelConFondo61.add(panelConFondo69);
        panelConFondo69.setBounds(90, 300, 110, 100);

        panelConFondo53.add(panelConFondo61);
        panelConFondo61.setBounds(90, 300, 110, 100);

        panelConFondo45.add(panelConFondo53);
        panelConFondo53.setBounds(90, 300, 110, 100);

        panelConFondo5.add(panelConFondo45);
        panelConFondo45.setBounds(90, 300, 110, 100);

        panelConFondo85.add(panelConFondo86);
        panelConFondo86.setBounds(90, 300, 110, 100);

        panelConFondo87.add(panelConFondo88);
        panelConFondo88.setBounds(90, 300, 110, 100);

        panelConFondo85.add(panelConFondo87);
        panelConFondo87.setBounds(90, 150, 110, 100);

        panelConFondo89.add(panelConFondo90);
        panelConFondo90.setBounds(90, 300, 110, 100);

        panelConFondo91.add(panelConFondo92);
        panelConFondo92.setBounds(90, 300, 110, 100);

        panelConFondo89.add(panelConFondo91);
        panelConFondo91.setBounds(90, 150, 110, 100);

        panelConFondo85.add(panelConFondo89);
        panelConFondo89.setBounds(90, 150, 110, 100);

        panelConFondo93.add(panelConFondo94);
        panelConFondo94.setBounds(90, 300, 110, 100);

        panelConFondo95.add(panelConFondo96);
        panelConFondo96.setBounds(90, 300, 110, 100);

        panelConFondo93.add(panelConFondo95);
        panelConFondo95.setBounds(90, 150, 110, 100);

        panelConFondo97.add(panelConFondo98);
        panelConFondo98.setBounds(90, 300, 110, 100);

        panelConFondo99.add(panelConFondo100);
        panelConFondo100.setBounds(90, 300, 110, 100);

        panelConFondo97.add(panelConFondo99);
        panelConFondo99.setBounds(90, 150, 110, 100);

        panelConFondo93.add(panelConFondo97);
        panelConFondo97.setBounds(90, 150, 110, 100);

        panelConFondo85.add(panelConFondo93);
        panelConFondo93.setBounds(90, 150, 110, 100);

        panelConFondo5.add(panelConFondo85);
        panelConFondo85.setBounds(90, 150, 110, 100);

        panelConFondo133.add(panelConFondo134);
        panelConFondo134.setBounds(90, 300, 110, 100);

        panelConFondo135.add(panelConFondo136);
        panelConFondo136.setBounds(90, 300, 110, 100);

        panelConFondo133.add(panelConFondo135);
        panelConFondo135.setBounds(90, 150, 110, 100);

        panelConFondo137.add(panelConFondo138);
        panelConFondo138.setBounds(90, 300, 110, 100);

        panelConFondo139.add(panelConFondo140);
        panelConFondo140.setBounds(90, 300, 110, 100);

        panelConFondo137.add(panelConFondo139);
        panelConFondo139.setBounds(90, 150, 110, 100);

        panelConFondo133.add(panelConFondo137);
        panelConFondo137.setBounds(90, 150, 110, 100);

        panelConFondo141.add(panelConFondo142);
        panelConFondo142.setBounds(90, 300, 110, 100);

        panelConFondo143.add(panelConFondo144);
        panelConFondo144.setBounds(90, 300, 110, 100);

        panelConFondo141.add(panelConFondo143);
        panelConFondo143.setBounds(90, 150, 110, 100);

        panelConFondo145.add(panelConFondo146);
        panelConFondo146.setBounds(90, 300, 110, 100);

        panelConFondo147.add(panelConFondo148);
        panelConFondo148.setBounds(90, 300, 110, 100);

        panelConFondo145.add(panelConFondo147);
        panelConFondo147.setBounds(90, 150, 110, 100);

        panelConFondo141.add(panelConFondo145);
        panelConFondo145.setBounds(90, 150, 110, 100);

        panelConFondo149.add(panelConFondo150);
        panelConFondo150.setBounds(90, 300, 110, 100);

        panelConFondo151.add(panelConFondo152);
        panelConFondo152.setBounds(90, 300, 110, 100);

        panelConFondo149.add(panelConFondo151);
        panelConFondo151.setBounds(90, 150, 110, 100);

        panelConFondo153.add(panelConFondo154);
        panelConFondo154.setBounds(90, 300, 110, 100);

        panelConFondo155.add(panelConFondo156);
        panelConFondo156.setBounds(90, 300, 110, 100);

        panelConFondo153.add(panelConFondo155);
        panelConFondo155.setBounds(90, 150, 110, 100);

        panelConFondo149.add(panelConFondo153);
        panelConFondo153.setBounds(90, 150, 110, 100);

        panelConFondo157.add(panelConFondo158);
        panelConFondo158.setBounds(90, 300, 110, 100);

        panelConFondo159.add(panelConFondo160);
        panelConFondo160.setBounds(90, 300, 110, 100);

        panelConFondo157.add(panelConFondo159);
        panelConFondo159.setBounds(90, 150, 110, 100);

        panelConFondo161.add(panelConFondo162);
        panelConFondo162.setBounds(90, 300, 110, 100);

        panelConFondo163.add(panelConFondo164);
        panelConFondo164.setBounds(90, 300, 110, 100);

        panelConFondo161.add(panelConFondo163);
        panelConFondo163.setBounds(90, 150, 110, 100);

        panelConFondo157.add(panelConFondo161);
        panelConFondo161.setBounds(90, 150, 110, 100);

        panelConFondo149.add(panelConFondo157);
        panelConFondo157.setBounds(90, 300, 110, 100);

        panelConFondo141.add(panelConFondo149);
        panelConFondo149.setBounds(90, 300, 110, 100);

        panelConFondo133.add(panelConFondo141);
        panelConFondo141.setBounds(90, 300, 110, 100);

        panelConFondo165.add(panelConFondo166);
        panelConFondo166.setBounds(90, 300, 110, 100);

        panelConFondo167.add(panelConFondo168);
        panelConFondo168.setBounds(90, 300, 110, 100);

        panelConFondo165.add(panelConFondo167);
        panelConFondo167.setBounds(90, 150, 110, 100);

        panelConFondo169.add(panelConFondo170);
        panelConFondo170.setBounds(90, 300, 110, 100);

        panelConFondo171.add(panelConFondo172);
        panelConFondo172.setBounds(90, 300, 110, 100);

        panelConFondo169.add(panelConFondo171);
        panelConFondo171.setBounds(90, 150, 110, 100);

        panelConFondo165.add(panelConFondo169);
        panelConFondo169.setBounds(90, 150, 110, 100);

        panelConFondo173.add(panelConFondo174);
        panelConFondo174.setBounds(90, 300, 110, 100);

        panelConFondo175.add(panelConFondo176);
        panelConFondo176.setBounds(90, 300, 110, 100);

        panelConFondo173.add(panelConFondo175);
        panelConFondo175.setBounds(90, 150, 110, 100);

        panelConFondo177.add(panelConFondo178);
        panelConFondo178.setBounds(90, 300, 110, 100);

        panelConFondo179.add(panelConFondo180);
        panelConFondo180.setBounds(90, 300, 110, 100);

        panelConFondo177.add(panelConFondo179);
        panelConFondo179.setBounds(90, 150, 110, 100);

        panelConFondo173.add(panelConFondo177);
        panelConFondo177.setBounds(90, 150, 110, 100);

        panelConFondo181.add(panelConFondo182);
        panelConFondo182.setBounds(90, 300, 110, 100);

        panelConFondo183.add(panelConFondo184);
        panelConFondo184.setBounds(90, 300, 110, 100);

        panelConFondo181.add(panelConFondo183);
        panelConFondo183.setBounds(90, 150, 110, 100);

        panelConFondo185.add(panelConFondo186);
        panelConFondo186.setBounds(90, 300, 110, 100);

        panelConFondo187.add(panelConFondo188);
        panelConFondo188.setBounds(90, 300, 110, 100);

        panelConFondo185.add(panelConFondo187);
        panelConFondo187.setBounds(90, 150, 110, 100);

        panelConFondo181.add(panelConFondo185);
        panelConFondo185.setBounds(90, 150, 110, 100);

        panelConFondo189.add(panelConFondo190);
        panelConFondo190.setBounds(90, 300, 110, 100);

        panelConFondo191.add(panelConFondo192);
        panelConFondo192.setBounds(90, 300, 110, 100);

        panelConFondo189.add(panelConFondo191);
        panelConFondo191.setBounds(90, 150, 110, 100);

        panelConFondo193.add(panelConFondo194);
        panelConFondo194.setBounds(90, 300, 110, 100);

        panelConFondo195.add(panelConFondo196);
        panelConFondo196.setBounds(90, 300, 110, 100);

        panelConFondo193.add(panelConFondo195);
        panelConFondo195.setBounds(90, 150, 110, 100);

        panelConFondo189.add(panelConFondo193);
        panelConFondo193.setBounds(90, 150, 110, 100);

        panelConFondo181.add(panelConFondo189);
        panelConFondo189.setBounds(90, 300, 110, 100);

        panelConFondo173.add(panelConFondo181);
        panelConFondo181.setBounds(90, 300, 110, 100);

        panelConFondo165.add(panelConFondo173);
        panelConFondo173.setBounds(90, 300, 110, 100);

        panelConFondo133.add(panelConFondo165);
        panelConFondo165.setBounds(90, 300, 110, 100);

        panelConFondo197.add(panelConFondo198);
        panelConFondo198.setBounds(90, 300, 110, 100);

        panelConFondo199.add(panelConFondo200);
        panelConFondo200.setBounds(90, 300, 110, 100);

        panelConFondo197.add(panelConFondo199);
        panelConFondo199.setBounds(90, 150, 110, 100);

        panelConFondo201.add(panelConFondo202);
        panelConFondo202.setBounds(90, 300, 110, 100);

        panelConFondo203.add(panelConFondo204);
        panelConFondo204.setBounds(90, 300, 110, 100);

        panelConFondo201.add(panelConFondo203);
        panelConFondo203.setBounds(90, 150, 110, 100);

        panelConFondo197.add(panelConFondo201);
        panelConFondo201.setBounds(90, 150, 110, 100);

        panelConFondo205.add(panelConFondo206);
        panelConFondo206.setBounds(90, 300, 110, 100);

        panelConFondo207.add(panelConFondo208);
        panelConFondo208.setBounds(90, 300, 110, 100);

        panelConFondo205.add(panelConFondo207);
        panelConFondo207.setBounds(90, 150, 110, 100);

        panelConFondo209.add(panelConFondo210);
        panelConFondo210.setBounds(90, 300, 110, 100);

        panelConFondo211.add(panelConFondo212);
        panelConFondo212.setBounds(90, 300, 110, 100);

        panelConFondo209.add(panelConFondo211);
        panelConFondo211.setBounds(90, 150, 110, 100);

        panelConFondo205.add(panelConFondo209);
        panelConFondo209.setBounds(90, 150, 110, 100);

        panelConFondo197.add(panelConFondo205);
        panelConFondo205.setBounds(90, 150, 110, 100);

        panelConFondo133.add(panelConFondo197);
        panelConFondo197.setBounds(90, 150, 110, 100);

        panelConFondo5.add(panelConFondo133);
        panelConFondo133.setBounds(90, 300, 110, 100);

        panelConFondo213.add(panelConFondo214);
        panelConFondo214.setBounds(90, 300, 110, 100);

        panelConFondo215.add(panelConFondo216);
        panelConFondo216.setBounds(90, 300, 110, 100);

        panelConFondo213.add(panelConFondo215);
        panelConFondo215.setBounds(90, 150, 110, 100);

        panelConFondo217.add(panelConFondo218);
        panelConFondo218.setBounds(90, 300, 110, 100);

        panelConFondo219.add(panelConFondo220);
        panelConFondo220.setBounds(90, 300, 110, 100);

        panelConFondo217.add(panelConFondo219);
        panelConFondo219.setBounds(90, 150, 110, 100);

        panelConFondo213.add(panelConFondo217);
        panelConFondo217.setBounds(90, 150, 110, 100);

        panelConFondo221.add(panelConFondo222);
        panelConFondo222.setBounds(90, 300, 110, 100);

        panelConFondo223.add(panelConFondo224);
        panelConFondo224.setBounds(90, 300, 110, 100);

        panelConFondo221.add(panelConFondo223);
        panelConFondo223.setBounds(90, 150, 110, 100);

        panelConFondo225.add(panelConFondo226);
        panelConFondo226.setBounds(90, 300, 110, 100);

        panelConFondo227.add(panelConFondo228);
        panelConFondo228.setBounds(90, 300, 110, 100);

        panelConFondo225.add(panelConFondo227);
        panelConFondo227.setBounds(90, 150, 110, 100);

        panelConFondo221.add(panelConFondo225);
        panelConFondo225.setBounds(90, 150, 110, 100);

        panelConFondo229.add(panelConFondo230);
        panelConFondo230.setBounds(90, 300, 110, 100);

        panelConFondo231.add(panelConFondo232);
        panelConFondo232.setBounds(90, 300, 110, 100);

        panelConFondo229.add(panelConFondo231);
        panelConFondo231.setBounds(90, 150, 110, 100);

        panelConFondo233.add(panelConFondo234);
        panelConFondo234.setBounds(90, 300, 110, 100);

        panelConFondo235.add(panelConFondo236);
        panelConFondo236.setBounds(90, 300, 110, 100);

        panelConFondo233.add(panelConFondo235);
        panelConFondo235.setBounds(90, 150, 110, 100);

        panelConFondo229.add(panelConFondo233);
        panelConFondo233.setBounds(90, 150, 110, 100);

        panelConFondo237.add(panelConFondo238);
        panelConFondo238.setBounds(90, 300, 110, 100);

        panelConFondo239.add(panelConFondo240);
        panelConFondo240.setBounds(90, 300, 110, 100);

        panelConFondo237.add(panelConFondo239);
        panelConFondo239.setBounds(90, 150, 110, 100);

        panelConFondo241.add(panelConFondo242);
        panelConFondo242.setBounds(90, 300, 110, 100);

        panelConFondo243.add(panelConFondo244);
        panelConFondo244.setBounds(90, 300, 110, 100);

        panelConFondo241.add(panelConFondo243);
        panelConFondo243.setBounds(90, 150, 110, 100);

        panelConFondo237.add(panelConFondo241);
        panelConFondo241.setBounds(90, 150, 110, 100);

        panelConFondo229.add(panelConFondo237);
        panelConFondo237.setBounds(90, 300, 110, 100);

        panelConFondo221.add(panelConFondo229);
        panelConFondo229.setBounds(90, 300, 110, 100);

        panelConFondo213.add(panelConFondo221);
        panelConFondo221.setBounds(90, 300, 110, 100);

        panelConFondo245.add(panelConFondo246);
        panelConFondo246.setBounds(90, 300, 110, 100);

        panelConFondo247.add(panelConFondo248);
        panelConFondo248.setBounds(90, 300, 110, 100);

        panelConFondo245.add(panelConFondo247);
        panelConFondo247.setBounds(90, 150, 110, 100);

        panelConFondo249.add(panelConFondo250);
        panelConFondo250.setBounds(90, 300, 110, 100);

        panelConFondo251.add(panelConFondo252);
        panelConFondo252.setBounds(90, 300, 110, 100);

        panelConFondo249.add(panelConFondo251);
        panelConFondo251.setBounds(90, 150, 110, 100);

        panelConFondo245.add(panelConFondo249);
        panelConFondo249.setBounds(90, 150, 110, 100);

        panelConFondo253.add(panelConFondo254);
        panelConFondo254.setBounds(90, 300, 110, 100);

        panelConFondo255.add(panelConFondo256);
        panelConFondo256.setBounds(90, 300, 110, 100);

        panelConFondo253.add(panelConFondo255);
        panelConFondo255.setBounds(90, 150, 110, 100);

        panelConFondo257.add(panelConFondo258);
        panelConFondo258.setBounds(90, 300, 110, 100);

        panelConFondo259.add(panelConFondo260);
        panelConFondo260.setBounds(90, 300, 110, 100);

        panelConFondo257.add(panelConFondo259);
        panelConFondo259.setBounds(90, 150, 110, 100);

        panelConFondo253.add(panelConFondo257);
        panelConFondo257.setBounds(90, 150, 110, 100);

        panelConFondo261.add(panelConFondo262);
        panelConFondo262.setBounds(90, 300, 110, 100);

        panelConFondo263.add(panelConFondo264);
        panelConFondo264.setBounds(90, 300, 110, 100);

        panelConFondo261.add(panelConFondo263);
        panelConFondo263.setBounds(90, 150, 110, 100);

        panelConFondo265.add(panelConFondo266);
        panelConFondo266.setBounds(90, 300, 110, 100);

        panelConFondo267.add(panelConFondo268);
        panelConFondo268.setBounds(90, 300, 110, 100);

        panelConFondo265.add(panelConFondo267);
        panelConFondo267.setBounds(90, 150, 110, 100);

        panelConFondo261.add(panelConFondo265);
        panelConFondo265.setBounds(90, 150, 110, 100);

        panelConFondo269.add(panelConFondo270);
        panelConFondo270.setBounds(90, 300, 110, 100);

        panelConFondo271.add(panelConFondo272);
        panelConFondo272.setBounds(90, 300, 110, 100);

        panelConFondo269.add(panelConFondo271);
        panelConFondo271.setBounds(90, 150, 110, 100);

        panelConFondo273.add(panelConFondo274);
        panelConFondo274.setBounds(90, 300, 110, 100);

        panelConFondo275.add(panelConFondo276);
        panelConFondo276.setBounds(90, 300, 110, 100);

        panelConFondo273.add(panelConFondo275);
        panelConFondo275.setBounds(90, 150, 110, 100);

        panelConFondo269.add(panelConFondo273);
        panelConFondo273.setBounds(90, 150, 110, 100);

        panelConFondo261.add(panelConFondo269);
        panelConFondo269.setBounds(90, 300, 110, 100);

        panelConFondo253.add(panelConFondo261);
        panelConFondo261.setBounds(90, 300, 110, 100);

        panelConFondo245.add(panelConFondo253);
        panelConFondo253.setBounds(90, 300, 110, 100);

        panelConFondo213.add(panelConFondo245);
        panelConFondo245.setBounds(90, 300, 110, 100);

        panelConFondo277.add(panelConFondo278);
        panelConFondo278.setBounds(90, 300, 110, 100);

        panelConFondo279.add(panelConFondo280);
        panelConFondo280.setBounds(90, 300, 110, 100);

        panelConFondo277.add(panelConFondo279);
        panelConFondo279.setBounds(90, 150, 110, 100);

        panelConFondo281.add(panelConFondo282);
        panelConFondo282.setBounds(90, 300, 110, 100);

        panelConFondo283.add(panelConFondo284);
        panelConFondo284.setBounds(90, 300, 110, 100);

        panelConFondo281.add(panelConFondo283);
        panelConFondo283.setBounds(90, 150, 110, 100);

        panelConFondo277.add(panelConFondo281);
        panelConFondo281.setBounds(90, 150, 110, 100);

        panelConFondo285.add(panelConFondo286);
        panelConFondo286.setBounds(90, 300, 110, 100);

        panelConFondo287.add(panelConFondo288);
        panelConFondo288.setBounds(90, 300, 110, 100);

        panelConFondo285.add(panelConFondo287);
        panelConFondo287.setBounds(90, 150, 110, 100);

        panelConFondo289.add(panelConFondo290);
        panelConFondo290.setBounds(90, 300, 110, 100);

        panelConFondo291.add(panelConFondo292);
        panelConFondo292.setBounds(90, 300, 110, 100);

        panelConFondo289.add(panelConFondo291);
        panelConFondo291.setBounds(90, 150, 110, 100);

        panelConFondo285.add(panelConFondo289);
        panelConFondo289.setBounds(90, 150, 110, 100);

        panelConFondo277.add(panelConFondo285);
        panelConFondo285.setBounds(90, 150, 110, 100);

        panelConFondo213.add(panelConFondo277);
        panelConFondo277.setBounds(90, 150, 110, 100);

        panelConFondo293.add(panelConFondo294);
        panelConFondo294.setBounds(90, 300, 110, 100);

        panelConFondo295.add(panelConFondo296);
        panelConFondo296.setBounds(90, 300, 110, 100);

        panelConFondo293.add(panelConFondo295);
        panelConFondo295.setBounds(90, 150, 110, 100);

        panelConFondo297.add(panelConFondo298);
        panelConFondo298.setBounds(90, 300, 110, 100);

        panelConFondo299.add(panelConFondo300);
        panelConFondo300.setBounds(90, 300, 110, 100);

        panelConFondo297.add(panelConFondo299);
        panelConFondo299.setBounds(90, 150, 110, 100);

        panelConFondo293.add(panelConFondo297);
        panelConFondo297.setBounds(90, 150, 110, 100);

        panelConFondo301.add(panelConFondo302);
        panelConFondo302.setBounds(90, 300, 110, 100);

        panelConFondo303.add(panelConFondo304);
        panelConFondo304.setBounds(90, 300, 110, 100);

        panelConFondo301.add(panelConFondo303);
        panelConFondo303.setBounds(90, 150, 110, 100);

        panelConFondo305.add(panelConFondo306);
        panelConFondo306.setBounds(90, 300, 110, 100);

        panelConFondo307.add(panelConFondo308);
        panelConFondo308.setBounds(90, 300, 110, 100);

        panelConFondo305.add(panelConFondo307);
        panelConFondo307.setBounds(90, 150, 110, 100);

        panelConFondo301.add(panelConFondo305);
        panelConFondo305.setBounds(90, 150, 110, 100);

        panelConFondo309.add(panelConFondo310);
        panelConFondo310.setBounds(90, 300, 110, 100);

        panelConFondo311.add(panelConFondo312);
        panelConFondo312.setBounds(90, 300, 110, 100);

        panelConFondo309.add(panelConFondo311);
        panelConFondo311.setBounds(90, 150, 110, 100);

        panelConFondo313.add(panelConFondo314);
        panelConFondo314.setBounds(90, 300, 110, 100);

        panelConFondo315.add(panelConFondo316);
        panelConFondo316.setBounds(90, 300, 110, 100);

        panelConFondo313.add(panelConFondo315);
        panelConFondo315.setBounds(90, 150, 110, 100);

        panelConFondo309.add(panelConFondo313);
        panelConFondo313.setBounds(90, 150, 110, 100);

        panelConFondo317.add(panelConFondo318);
        panelConFondo318.setBounds(90, 300, 110, 100);

        panelConFondo319.add(panelConFondo320);
        panelConFondo320.setBounds(90, 300, 110, 100);

        panelConFondo317.add(panelConFondo319);
        panelConFondo319.setBounds(90, 150, 110, 100);

        panelConFondo321.add(panelConFondo322);
        panelConFondo322.setBounds(90, 300, 110, 100);

        panelConFondo323.add(panelConFondo324);
        panelConFondo324.setBounds(90, 300, 110, 100);

        panelConFondo321.add(panelConFondo323);
        panelConFondo323.setBounds(90, 150, 110, 100);

        panelConFondo317.add(panelConFondo321);
        panelConFondo321.setBounds(90, 150, 110, 100);

        panelConFondo309.add(panelConFondo317);
        panelConFondo317.setBounds(90, 300, 110, 100);

        panelConFondo301.add(panelConFondo309);
        panelConFondo309.setBounds(90, 300, 110, 100);

        panelConFondo293.add(panelConFondo301);
        panelConFondo301.setBounds(90, 300, 110, 100);

        panelConFondo325.add(panelConFondo326);
        panelConFondo326.setBounds(90, 300, 110, 100);

        panelConFondo327.add(panelConFondo328);
        panelConFondo328.setBounds(90, 300, 110, 100);

        panelConFondo325.add(panelConFondo327);
        panelConFondo327.setBounds(90, 150, 110, 100);

        panelConFondo329.add(panelConFondo330);
        panelConFondo330.setBounds(90, 300, 110, 100);

        panelConFondo331.add(panelConFondo332);
        panelConFondo332.setBounds(90, 300, 110, 100);

        panelConFondo329.add(panelConFondo331);
        panelConFondo331.setBounds(90, 150, 110, 100);

        panelConFondo325.add(panelConFondo329);
        panelConFondo329.setBounds(90, 150, 110, 100);

        panelConFondo333.add(panelConFondo334);
        panelConFondo334.setBounds(90, 300, 110, 100);

        panelConFondo335.add(panelConFondo336);
        panelConFondo336.setBounds(90, 300, 110, 100);

        panelConFondo333.add(panelConFondo335);
        panelConFondo335.setBounds(90, 150, 110, 100);

        panelConFondo337.add(panelConFondo338);
        panelConFondo338.setBounds(90, 300, 110, 100);

        panelConFondo339.add(panelConFondo340);
        panelConFondo340.setBounds(90, 300, 110, 100);

        panelConFondo337.add(panelConFondo339);
        panelConFondo339.setBounds(90, 150, 110, 100);

        panelConFondo333.add(panelConFondo337);
        panelConFondo337.setBounds(90, 150, 110, 100);

        panelConFondo341.add(panelConFondo342);
        panelConFondo342.setBounds(90, 300, 110, 100);

        panelConFondo343.add(panelConFondo344);
        panelConFondo344.setBounds(90, 300, 110, 100);

        panelConFondo341.add(panelConFondo343);
        panelConFondo343.setBounds(90, 150, 110, 100);

        panelConFondo345.add(panelConFondo346);
        panelConFondo346.setBounds(90, 300, 110, 100);

        panelConFondo347.add(panelConFondo348);
        panelConFondo348.setBounds(90, 300, 110, 100);

        panelConFondo345.add(panelConFondo347);
        panelConFondo347.setBounds(90, 150, 110, 100);

        panelConFondo341.add(panelConFondo345);
        panelConFondo345.setBounds(90, 150, 110, 100);

        panelConFondo349.add(panelConFondo350);
        panelConFondo350.setBounds(90, 300, 110, 100);

        panelConFondo351.add(panelConFondo352);
        panelConFondo352.setBounds(90, 300, 110, 100);

        panelConFondo349.add(panelConFondo351);
        panelConFondo351.setBounds(90, 150, 110, 100);

        panelConFondo353.add(panelConFondo354);
        panelConFondo354.setBounds(90, 300, 110, 100);

        panelConFondo355.add(panelConFondo356);
        panelConFondo356.setBounds(90, 300, 110, 100);

        panelConFondo353.add(panelConFondo355);
        panelConFondo355.setBounds(90, 150, 110, 100);

        panelConFondo349.add(panelConFondo353);
        panelConFondo353.setBounds(90, 150, 110, 100);

        panelConFondo341.add(panelConFondo349);
        panelConFondo349.setBounds(90, 300, 110, 100);

        panelConFondo333.add(panelConFondo341);
        panelConFondo341.setBounds(90, 300, 110, 100);

        panelConFondo325.add(panelConFondo333);
        panelConFondo333.setBounds(90, 300, 110, 100);

        panelConFondo293.add(panelConFondo325);
        panelConFondo325.setBounds(90, 300, 110, 100);

        panelConFondo357.add(panelConFondo358);
        panelConFondo358.setBounds(90, 300, 110, 100);

        panelConFondo359.add(panelConFondo360);
        panelConFondo360.setBounds(90, 300, 110, 100);

        panelConFondo357.add(panelConFondo359);
        panelConFondo359.setBounds(90, 150, 110, 100);

        panelConFondo361.add(panelConFondo362);
        panelConFondo362.setBounds(90, 300, 110, 100);

        panelConFondo363.add(panelConFondo364);
        panelConFondo364.setBounds(90, 300, 110, 100);

        panelConFondo361.add(panelConFondo363);
        panelConFondo363.setBounds(90, 150, 110, 100);

        panelConFondo357.add(panelConFondo361);
        panelConFondo361.setBounds(90, 150, 110, 100);

        panelConFondo365.add(panelConFondo366);
        panelConFondo366.setBounds(90, 300, 110, 100);

        panelConFondo367.add(panelConFondo368);
        panelConFondo368.setBounds(90, 300, 110, 100);

        panelConFondo365.add(panelConFondo367);
        panelConFondo367.setBounds(90, 150, 110, 100);

        panelConFondo369.add(panelConFondo370);
        panelConFondo370.setBounds(90, 300, 110, 100);

        panelConFondo371.add(panelConFondo372);
        panelConFondo372.setBounds(90, 300, 110, 100);

        panelConFondo369.add(panelConFondo371);
        panelConFondo371.setBounds(90, 150, 110, 100);

        panelConFondo365.add(panelConFondo369);
        panelConFondo369.setBounds(90, 150, 110, 100);

        panelConFondo357.add(panelConFondo365);
        panelConFondo365.setBounds(90, 150, 110, 100);

        panelConFondo293.add(panelConFondo357);
        panelConFondo357.setBounds(90, 150, 110, 100);

        panelConFondo213.add(panelConFondo293);
        panelConFondo293.setBounds(90, 300, 110, 100);

        panelConFondo5.add(panelConFondo213);
        panelConFondo213.setBounds(90, 300, 110, 100);

        panelClientes.add(panelConFondo5);
        panelConFondo5.setBounds(90, 320, 110, 100);

        panelConFondo13.add(panelConFondo14);
        panelConFondo14.setBounds(90, 300, 110, 100);

        panelConFondo15.add(panelConFondo16);
        panelConFondo16.setBounds(90, 300, 110, 100);

        panelConFondo13.add(panelConFondo15);
        panelConFondo15.setBounds(90, 150, 110, 100);

        panelConFondo17.add(panelConFondo18);
        panelConFondo18.setBounds(90, 300, 110, 100);

        panelConFondo19.add(panelConFondo20);
        panelConFondo20.setBounds(90, 300, 110, 100);

        panelConFondo17.add(panelConFondo19);
        panelConFondo19.setBounds(90, 150, 110, 100);

        panelConFondo13.add(panelConFondo17);
        panelConFondo17.setBounds(90, 150, 110, 100);

        panelConFondo77.add(panelConFondo78);
        panelConFondo78.setBounds(90, 300, 110, 100);

        panelConFondo79.add(panelConFondo80);
        panelConFondo80.setBounds(90, 300, 110, 100);

        panelConFondo77.add(panelConFondo79);
        panelConFondo79.setBounds(90, 150, 110, 100);

        panelConFondo81.add(panelConFondo82);
        panelConFondo82.setBounds(90, 300, 110, 100);

        panelConFondo83.add(panelConFondo84);
        panelConFondo84.setBounds(90, 300, 110, 100);

        panelConFondo81.add(panelConFondo83);
        panelConFondo83.setBounds(90, 150, 110, 100);

        panelConFondo77.add(panelConFondo81);
        panelConFondo81.setBounds(90, 150, 110, 100);

        panelConFondo13.add(panelConFondo77);
        panelConFondo77.setBounds(90, 150, 110, 100);

        panelConFondo117.add(panelConFondo118);
        panelConFondo118.setBounds(90, 300, 110, 100);

        panelConFondo119.add(panelConFondo120);
        panelConFondo120.setBounds(90, 300, 110, 100);

        panelConFondo117.add(panelConFondo119);
        panelConFondo119.setBounds(90, 150, 110, 100);

        panelConFondo121.add(panelConFondo122);
        panelConFondo122.setBounds(90, 300, 110, 100);

        panelConFondo123.add(panelConFondo124);
        panelConFondo124.setBounds(90, 300, 110, 100);

        panelConFondo121.add(panelConFondo123);
        panelConFondo123.setBounds(90, 150, 110, 100);

        panelConFondo117.add(panelConFondo121);
        panelConFondo121.setBounds(90, 150, 110, 100);

        panelConFondo125.add(panelConFondo126);
        panelConFondo126.setBounds(90, 300, 110, 100);

        panelConFondo127.add(panelConFondo128);
        panelConFondo128.setBounds(90, 300, 110, 100);

        panelConFondo125.add(panelConFondo127);
        panelConFondo127.setBounds(90, 150, 110, 100);

        panelConFondo129.add(panelConFondo130);
        panelConFondo130.setBounds(90, 300, 110, 100);

        panelConFondo131.add(panelConFondo132);
        panelConFondo132.setBounds(90, 300, 110, 100);

        panelConFondo129.add(panelConFondo131);
        panelConFondo131.setBounds(90, 150, 110, 100);

        panelConFondo125.add(panelConFondo129);
        panelConFondo129.setBounds(90, 150, 110, 100);

        panelConFondo117.add(panelConFondo125);
        panelConFondo125.setBounds(90, 150, 110, 100);

        panelConFondo13.add(panelConFondo117);
        panelConFondo117.setBounds(90, 150, 110, 100);

        panelConFondo373.add(panelConFondo374);
        panelConFondo374.setBounds(90, 300, 110, 100);

        panelConFondo375.add(panelConFondo376);
        panelConFondo376.setBounds(90, 300, 110, 100);

        panelConFondo373.add(panelConFondo375);
        panelConFondo375.setBounds(90, 150, 110, 100);

        panelConFondo377.add(panelConFondo378);
        panelConFondo378.setBounds(90, 300, 110, 100);

        panelConFondo379.add(panelConFondo380);
        panelConFondo380.setBounds(90, 300, 110, 100);

        panelConFondo377.add(panelConFondo379);
        panelConFondo379.setBounds(90, 150, 110, 100);

        panelConFondo373.add(panelConFondo377);
        panelConFondo377.setBounds(90, 150, 110, 100);

        panelConFondo381.add(panelConFondo382);
        panelConFondo382.setBounds(90, 300, 110, 100);

        panelConFondo383.add(panelConFondo384);
        panelConFondo384.setBounds(90, 300, 110, 100);

        panelConFondo381.add(panelConFondo383);
        panelConFondo383.setBounds(90, 150, 110, 100);

        panelConFondo385.add(panelConFondo386);
        panelConFondo386.setBounds(90, 300, 110, 100);

        panelConFondo387.add(panelConFondo388);
        panelConFondo388.setBounds(90, 300, 110, 100);

        panelConFondo385.add(panelConFondo387);
        panelConFondo387.setBounds(90, 150, 110, 100);

        panelConFondo381.add(panelConFondo385);
        panelConFondo385.setBounds(90, 150, 110, 100);

        panelConFondo373.add(panelConFondo381);
        panelConFondo381.setBounds(90, 150, 110, 100);

        panelConFondo389.add(panelConFondo390);
        panelConFondo390.setBounds(90, 300, 110, 100);

        panelConFondo391.add(panelConFondo392);
        panelConFondo392.setBounds(90, 300, 110, 100);

        panelConFondo389.add(panelConFondo391);
        panelConFondo391.setBounds(90, 150, 110, 100);

        panelConFondo393.add(panelConFondo394);
        panelConFondo394.setBounds(90, 300, 110, 100);

        panelConFondo395.add(panelConFondo396);
        panelConFondo396.setBounds(90, 300, 110, 100);

        panelConFondo393.add(panelConFondo395);
        panelConFondo395.setBounds(90, 150, 110, 100);

        panelConFondo389.add(panelConFondo393);
        panelConFondo393.setBounds(90, 150, 110, 100);

        panelConFondo397.add(panelConFondo398);
        panelConFondo398.setBounds(90, 300, 110, 100);

        panelConFondo399.add(panelConFondo400);
        panelConFondo400.setBounds(90, 300, 110, 100);

        panelConFondo397.add(panelConFondo399);
        panelConFondo399.setBounds(90, 150, 110, 100);

        panelConFondo401.add(panelConFondo402);
        panelConFondo402.setBounds(90, 300, 110, 100);

        panelConFondo403.add(panelConFondo404);
        panelConFondo404.setBounds(90, 300, 110, 100);

        panelConFondo401.add(panelConFondo403);
        panelConFondo403.setBounds(90, 150, 110, 100);

        panelConFondo397.add(panelConFondo401);
        panelConFondo401.setBounds(90, 150, 110, 100);

        panelConFondo389.add(panelConFondo397);
        panelConFondo397.setBounds(90, 150, 110, 100);

        panelConFondo373.add(panelConFondo389);
        panelConFondo389.setBounds(90, 150, 110, 100);

        panelConFondo13.add(panelConFondo373);
        panelConFondo373.setBounds(90, 150, 110, 100);

        panelClientes.add(panelConFondo13);
        panelConFondo13.setBounds(90, 170, 110, 100);
        panelClientes.add(panelConFondo405);
        panelConFondo405.setBounds(90, 20, 110, 100);

        txtSigue.setEditable(false);
        txtSigue.setColumns(20);
        txtSigue.setRows(5);
        jScrollPane3.setViewportView(txtSigue);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        transparentTextArea1.setEditable(false);
        transparentTextArea1.setColumns(20);
        transparentTextArea1.setRows(5);
        transparentTextArea1.setText("  En este momento estamos \n  atendiendo:");
        transparentTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jScrollPane2.setViewportView(transparentTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(90, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPlataforma1;
    private javax.swing.JLabel lblPlataforma3;
    private javax.swing.JLabel lblPlataforma4;
    private javax.swing.JLabel lblTituloCuentas;
    private javax.swing.JLabel lblTituloPlataforma;
    private javax.swing.JLabel lblTituloTramites;
    private sacoba.vista.PanelConFondo panelClientes;
    private sacoba.vista.PanelConFondo panelConFondo1;
    private sacoba.vista.PanelConFondo panelConFondo10;
    private sacoba.vista.PanelConFondo panelConFondo100;
    private sacoba.vista.PanelConFondo panelConFondo101;
    private sacoba.vista.PanelConFondo panelConFondo102;
    private sacoba.vista.PanelConFondo panelConFondo103;
    private sacoba.vista.PanelConFondo panelConFondo104;
    private sacoba.vista.PanelConFondo panelConFondo105;
    private sacoba.vista.PanelConFondo panelConFondo106;
    private sacoba.vista.PanelConFondo panelConFondo107;
    private sacoba.vista.PanelConFondo panelConFondo108;
    private sacoba.vista.PanelConFondo panelConFondo109;
    private sacoba.vista.PanelConFondo panelConFondo11;
    private sacoba.vista.PanelConFondo panelConFondo110;
    private sacoba.vista.PanelConFondo panelConFondo111;
    private sacoba.vista.PanelConFondo panelConFondo112;
    private sacoba.vista.PanelConFondo panelConFondo113;
    private sacoba.vista.PanelConFondo panelConFondo114;
    private sacoba.vista.PanelConFondo panelConFondo115;
    private sacoba.vista.PanelConFondo panelConFondo116;
    private sacoba.vista.PanelConFondo panelConFondo117;
    private sacoba.vista.PanelConFondo panelConFondo118;
    private sacoba.vista.PanelConFondo panelConFondo119;
    private sacoba.vista.PanelConFondo panelConFondo12;
    private sacoba.vista.PanelConFondo panelConFondo120;
    private sacoba.vista.PanelConFondo panelConFondo121;
    private sacoba.vista.PanelConFondo panelConFondo122;
    private sacoba.vista.PanelConFondo panelConFondo123;
    private sacoba.vista.PanelConFondo panelConFondo124;
    private sacoba.vista.PanelConFondo panelConFondo125;
    private sacoba.vista.PanelConFondo panelConFondo126;
    private sacoba.vista.PanelConFondo panelConFondo127;
    private sacoba.vista.PanelConFondo panelConFondo128;
    private sacoba.vista.PanelConFondo panelConFondo129;
    private sacoba.vista.PanelConFondo panelConFondo13;
    private sacoba.vista.PanelConFondo panelConFondo130;
    private sacoba.vista.PanelConFondo panelConFondo131;
    private sacoba.vista.PanelConFondo panelConFondo132;
    private sacoba.vista.PanelConFondo panelConFondo133;
    private sacoba.vista.PanelConFondo panelConFondo134;
    private sacoba.vista.PanelConFondo panelConFondo135;
    private sacoba.vista.PanelConFondo panelConFondo136;
    private sacoba.vista.PanelConFondo panelConFondo137;
    private sacoba.vista.PanelConFondo panelConFondo138;
    private sacoba.vista.PanelConFondo panelConFondo139;
    private sacoba.vista.PanelConFondo panelConFondo14;
    private sacoba.vista.PanelConFondo panelConFondo140;
    private sacoba.vista.PanelConFondo panelConFondo141;
    private sacoba.vista.PanelConFondo panelConFondo142;
    private sacoba.vista.PanelConFondo panelConFondo143;
    private sacoba.vista.PanelConFondo panelConFondo144;
    private sacoba.vista.PanelConFondo panelConFondo145;
    private sacoba.vista.PanelConFondo panelConFondo146;
    private sacoba.vista.PanelConFondo panelConFondo147;
    private sacoba.vista.PanelConFondo panelConFondo148;
    private sacoba.vista.PanelConFondo panelConFondo149;
    private sacoba.vista.PanelConFondo panelConFondo15;
    private sacoba.vista.PanelConFondo panelConFondo150;
    private sacoba.vista.PanelConFondo panelConFondo151;
    private sacoba.vista.PanelConFondo panelConFondo152;
    private sacoba.vista.PanelConFondo panelConFondo153;
    private sacoba.vista.PanelConFondo panelConFondo154;
    private sacoba.vista.PanelConFondo panelConFondo155;
    private sacoba.vista.PanelConFondo panelConFondo156;
    private sacoba.vista.PanelConFondo panelConFondo157;
    private sacoba.vista.PanelConFondo panelConFondo158;
    private sacoba.vista.PanelConFondo panelConFondo159;
    private sacoba.vista.PanelConFondo panelConFondo16;
    private sacoba.vista.PanelConFondo panelConFondo160;
    private sacoba.vista.PanelConFondo panelConFondo161;
    private sacoba.vista.PanelConFondo panelConFondo162;
    private sacoba.vista.PanelConFondo panelConFondo163;
    private sacoba.vista.PanelConFondo panelConFondo164;
    private sacoba.vista.PanelConFondo panelConFondo165;
    private sacoba.vista.PanelConFondo panelConFondo166;
    private sacoba.vista.PanelConFondo panelConFondo167;
    private sacoba.vista.PanelConFondo panelConFondo168;
    private sacoba.vista.PanelConFondo panelConFondo169;
    private sacoba.vista.PanelConFondo panelConFondo17;
    private sacoba.vista.PanelConFondo panelConFondo170;
    private sacoba.vista.PanelConFondo panelConFondo171;
    private sacoba.vista.PanelConFondo panelConFondo172;
    private sacoba.vista.PanelConFondo panelConFondo173;
    private sacoba.vista.PanelConFondo panelConFondo174;
    private sacoba.vista.PanelConFondo panelConFondo175;
    private sacoba.vista.PanelConFondo panelConFondo176;
    private sacoba.vista.PanelConFondo panelConFondo177;
    private sacoba.vista.PanelConFondo panelConFondo178;
    private sacoba.vista.PanelConFondo panelConFondo179;
    private sacoba.vista.PanelConFondo panelConFondo18;
    private sacoba.vista.PanelConFondo panelConFondo180;
    private sacoba.vista.PanelConFondo panelConFondo181;
    private sacoba.vista.PanelConFondo panelConFondo182;
    private sacoba.vista.PanelConFondo panelConFondo183;
    private sacoba.vista.PanelConFondo panelConFondo184;
    private sacoba.vista.PanelConFondo panelConFondo185;
    private sacoba.vista.PanelConFondo panelConFondo186;
    private sacoba.vista.PanelConFondo panelConFondo187;
    private sacoba.vista.PanelConFondo panelConFondo188;
    private sacoba.vista.PanelConFondo panelConFondo189;
    private sacoba.vista.PanelConFondo panelConFondo19;
    private sacoba.vista.PanelConFondo panelConFondo190;
    private sacoba.vista.PanelConFondo panelConFondo191;
    private sacoba.vista.PanelConFondo panelConFondo192;
    private sacoba.vista.PanelConFondo panelConFondo193;
    private sacoba.vista.PanelConFondo panelConFondo194;
    private sacoba.vista.PanelConFondo panelConFondo195;
    private sacoba.vista.PanelConFondo panelConFondo196;
    private sacoba.vista.PanelConFondo panelConFondo197;
    private sacoba.vista.PanelConFondo panelConFondo198;
    private sacoba.vista.PanelConFondo panelConFondo199;
    private sacoba.vista.PanelConFondo panelConFondo2;
    private sacoba.vista.PanelConFondo panelConFondo20;
    private sacoba.vista.PanelConFondo panelConFondo200;
    private sacoba.vista.PanelConFondo panelConFondo201;
    private sacoba.vista.PanelConFondo panelConFondo202;
    private sacoba.vista.PanelConFondo panelConFondo203;
    private sacoba.vista.PanelConFondo panelConFondo204;
    private sacoba.vista.PanelConFondo panelConFondo205;
    private sacoba.vista.PanelConFondo panelConFondo206;
    private sacoba.vista.PanelConFondo panelConFondo207;
    private sacoba.vista.PanelConFondo panelConFondo208;
    private sacoba.vista.PanelConFondo panelConFondo209;
    private sacoba.vista.PanelConFondo panelConFondo21;
    private sacoba.vista.PanelConFondo panelConFondo210;
    private sacoba.vista.PanelConFondo panelConFondo211;
    private sacoba.vista.PanelConFondo panelConFondo212;
    private sacoba.vista.PanelConFondo panelConFondo213;
    private sacoba.vista.PanelConFondo panelConFondo214;
    private sacoba.vista.PanelConFondo panelConFondo215;
    private sacoba.vista.PanelConFondo panelConFondo216;
    private sacoba.vista.PanelConFondo panelConFondo217;
    private sacoba.vista.PanelConFondo panelConFondo218;
    private sacoba.vista.PanelConFondo panelConFondo219;
    private sacoba.vista.PanelConFondo panelConFondo22;
    private sacoba.vista.PanelConFondo panelConFondo220;
    private sacoba.vista.PanelConFondo panelConFondo221;
    private sacoba.vista.PanelConFondo panelConFondo222;
    private sacoba.vista.PanelConFondo panelConFondo223;
    private sacoba.vista.PanelConFondo panelConFondo224;
    private sacoba.vista.PanelConFondo panelConFondo225;
    private sacoba.vista.PanelConFondo panelConFondo226;
    private sacoba.vista.PanelConFondo panelConFondo227;
    private sacoba.vista.PanelConFondo panelConFondo228;
    private sacoba.vista.PanelConFondo panelConFondo229;
    private sacoba.vista.PanelConFondo panelConFondo23;
    private sacoba.vista.PanelConFondo panelConFondo230;
    private sacoba.vista.PanelConFondo panelConFondo231;
    private sacoba.vista.PanelConFondo panelConFondo232;
    private sacoba.vista.PanelConFondo panelConFondo233;
    private sacoba.vista.PanelConFondo panelConFondo234;
    private sacoba.vista.PanelConFondo panelConFondo235;
    private sacoba.vista.PanelConFondo panelConFondo236;
    private sacoba.vista.PanelConFondo panelConFondo237;
    private sacoba.vista.PanelConFondo panelConFondo238;
    private sacoba.vista.PanelConFondo panelConFondo239;
    private sacoba.vista.PanelConFondo panelConFondo24;
    private sacoba.vista.PanelConFondo panelConFondo240;
    private sacoba.vista.PanelConFondo panelConFondo241;
    private sacoba.vista.PanelConFondo panelConFondo242;
    private sacoba.vista.PanelConFondo panelConFondo243;
    private sacoba.vista.PanelConFondo panelConFondo244;
    private sacoba.vista.PanelConFondo panelConFondo245;
    private sacoba.vista.PanelConFondo panelConFondo246;
    private sacoba.vista.PanelConFondo panelConFondo247;
    private sacoba.vista.PanelConFondo panelConFondo248;
    private sacoba.vista.PanelConFondo panelConFondo249;
    private sacoba.vista.PanelConFondo panelConFondo25;
    private sacoba.vista.PanelConFondo panelConFondo250;
    private sacoba.vista.PanelConFondo panelConFondo251;
    private sacoba.vista.PanelConFondo panelConFondo252;
    private sacoba.vista.PanelConFondo panelConFondo253;
    private sacoba.vista.PanelConFondo panelConFondo254;
    private sacoba.vista.PanelConFondo panelConFondo255;
    private sacoba.vista.PanelConFondo panelConFondo256;
    private sacoba.vista.PanelConFondo panelConFondo257;
    private sacoba.vista.PanelConFondo panelConFondo258;
    private sacoba.vista.PanelConFondo panelConFondo259;
    private sacoba.vista.PanelConFondo panelConFondo26;
    private sacoba.vista.PanelConFondo panelConFondo260;
    private sacoba.vista.PanelConFondo panelConFondo261;
    private sacoba.vista.PanelConFondo panelConFondo262;
    private sacoba.vista.PanelConFondo panelConFondo263;
    private sacoba.vista.PanelConFondo panelConFondo264;
    private sacoba.vista.PanelConFondo panelConFondo265;
    private sacoba.vista.PanelConFondo panelConFondo266;
    private sacoba.vista.PanelConFondo panelConFondo267;
    private sacoba.vista.PanelConFondo panelConFondo268;
    private sacoba.vista.PanelConFondo panelConFondo269;
    private sacoba.vista.PanelConFondo panelConFondo27;
    private sacoba.vista.PanelConFondo panelConFondo270;
    private sacoba.vista.PanelConFondo panelConFondo271;
    private sacoba.vista.PanelConFondo panelConFondo272;
    private sacoba.vista.PanelConFondo panelConFondo273;
    private sacoba.vista.PanelConFondo panelConFondo274;
    private sacoba.vista.PanelConFondo panelConFondo275;
    private sacoba.vista.PanelConFondo panelConFondo276;
    private sacoba.vista.PanelConFondo panelConFondo277;
    private sacoba.vista.PanelConFondo panelConFondo278;
    private sacoba.vista.PanelConFondo panelConFondo279;
    private sacoba.vista.PanelConFondo panelConFondo28;
    private sacoba.vista.PanelConFondo panelConFondo280;
    private sacoba.vista.PanelConFondo panelConFondo281;
    private sacoba.vista.PanelConFondo panelConFondo282;
    private sacoba.vista.PanelConFondo panelConFondo283;
    private sacoba.vista.PanelConFondo panelConFondo284;
    private sacoba.vista.PanelConFondo panelConFondo285;
    private sacoba.vista.PanelConFondo panelConFondo286;
    private sacoba.vista.PanelConFondo panelConFondo287;
    private sacoba.vista.PanelConFondo panelConFondo288;
    private sacoba.vista.PanelConFondo panelConFondo289;
    private sacoba.vista.PanelConFondo panelConFondo29;
    private sacoba.vista.PanelConFondo panelConFondo290;
    private sacoba.vista.PanelConFondo panelConFondo291;
    private sacoba.vista.PanelConFondo panelConFondo292;
    private sacoba.vista.PanelConFondo panelConFondo293;
    private sacoba.vista.PanelConFondo panelConFondo294;
    private sacoba.vista.PanelConFondo panelConFondo295;
    private sacoba.vista.PanelConFondo panelConFondo296;
    private sacoba.vista.PanelConFondo panelConFondo297;
    private sacoba.vista.PanelConFondo panelConFondo298;
    private sacoba.vista.PanelConFondo panelConFondo299;
    private sacoba.vista.PanelConFondo panelConFondo3;
    private sacoba.vista.PanelConFondo panelConFondo30;
    private sacoba.vista.PanelConFondo panelConFondo300;
    private sacoba.vista.PanelConFondo panelConFondo301;
    private sacoba.vista.PanelConFondo panelConFondo302;
    private sacoba.vista.PanelConFondo panelConFondo303;
    private sacoba.vista.PanelConFondo panelConFondo304;
    private sacoba.vista.PanelConFondo panelConFondo305;
    private sacoba.vista.PanelConFondo panelConFondo306;
    private sacoba.vista.PanelConFondo panelConFondo307;
    private sacoba.vista.PanelConFondo panelConFondo308;
    private sacoba.vista.PanelConFondo panelConFondo309;
    private sacoba.vista.PanelConFondo panelConFondo31;
    private sacoba.vista.PanelConFondo panelConFondo310;
    private sacoba.vista.PanelConFondo panelConFondo311;
    private sacoba.vista.PanelConFondo panelConFondo312;
    private sacoba.vista.PanelConFondo panelConFondo313;
    private sacoba.vista.PanelConFondo panelConFondo314;
    private sacoba.vista.PanelConFondo panelConFondo315;
    private sacoba.vista.PanelConFondo panelConFondo316;
    private sacoba.vista.PanelConFondo panelConFondo317;
    private sacoba.vista.PanelConFondo panelConFondo318;
    private sacoba.vista.PanelConFondo panelConFondo319;
    private sacoba.vista.PanelConFondo panelConFondo32;
    private sacoba.vista.PanelConFondo panelConFondo320;
    private sacoba.vista.PanelConFondo panelConFondo321;
    private sacoba.vista.PanelConFondo panelConFondo322;
    private sacoba.vista.PanelConFondo panelConFondo323;
    private sacoba.vista.PanelConFondo panelConFondo324;
    private sacoba.vista.PanelConFondo panelConFondo325;
    private sacoba.vista.PanelConFondo panelConFondo326;
    private sacoba.vista.PanelConFondo panelConFondo327;
    private sacoba.vista.PanelConFondo panelConFondo328;
    private sacoba.vista.PanelConFondo panelConFondo329;
    private sacoba.vista.PanelConFondo panelConFondo33;
    private sacoba.vista.PanelConFondo panelConFondo330;
    private sacoba.vista.PanelConFondo panelConFondo331;
    private sacoba.vista.PanelConFondo panelConFondo332;
    private sacoba.vista.PanelConFondo panelConFondo333;
    private sacoba.vista.PanelConFondo panelConFondo334;
    private sacoba.vista.PanelConFondo panelConFondo335;
    private sacoba.vista.PanelConFondo panelConFondo336;
    private sacoba.vista.PanelConFondo panelConFondo337;
    private sacoba.vista.PanelConFondo panelConFondo338;
    private sacoba.vista.PanelConFondo panelConFondo339;
    private sacoba.vista.PanelConFondo panelConFondo34;
    private sacoba.vista.PanelConFondo panelConFondo340;
    private sacoba.vista.PanelConFondo panelConFondo341;
    private sacoba.vista.PanelConFondo panelConFondo342;
    private sacoba.vista.PanelConFondo panelConFondo343;
    private sacoba.vista.PanelConFondo panelConFondo344;
    private sacoba.vista.PanelConFondo panelConFondo345;
    private sacoba.vista.PanelConFondo panelConFondo346;
    private sacoba.vista.PanelConFondo panelConFondo347;
    private sacoba.vista.PanelConFondo panelConFondo348;
    private sacoba.vista.PanelConFondo panelConFondo349;
    private sacoba.vista.PanelConFondo panelConFondo35;
    private sacoba.vista.PanelConFondo panelConFondo350;
    private sacoba.vista.PanelConFondo panelConFondo351;
    private sacoba.vista.PanelConFondo panelConFondo352;
    private sacoba.vista.PanelConFondo panelConFondo353;
    private sacoba.vista.PanelConFondo panelConFondo354;
    private sacoba.vista.PanelConFondo panelConFondo355;
    private sacoba.vista.PanelConFondo panelConFondo356;
    private sacoba.vista.PanelConFondo panelConFondo357;
    private sacoba.vista.PanelConFondo panelConFondo358;
    private sacoba.vista.PanelConFondo panelConFondo359;
    private sacoba.vista.PanelConFondo panelConFondo36;
    private sacoba.vista.PanelConFondo panelConFondo360;
    private sacoba.vista.PanelConFondo panelConFondo361;
    private sacoba.vista.PanelConFondo panelConFondo362;
    private sacoba.vista.PanelConFondo panelConFondo363;
    private sacoba.vista.PanelConFondo panelConFondo364;
    private sacoba.vista.PanelConFondo panelConFondo365;
    private sacoba.vista.PanelConFondo panelConFondo366;
    private sacoba.vista.PanelConFondo panelConFondo367;
    private sacoba.vista.PanelConFondo panelConFondo368;
    private sacoba.vista.PanelConFondo panelConFondo369;
    private sacoba.vista.PanelConFondo panelConFondo37;
    private sacoba.vista.PanelConFondo panelConFondo370;
    private sacoba.vista.PanelConFondo panelConFondo371;
    private sacoba.vista.PanelConFondo panelConFondo372;
    private sacoba.vista.PanelConFondo panelConFondo373;
    private sacoba.vista.PanelConFondo panelConFondo374;
    private sacoba.vista.PanelConFondo panelConFondo375;
    private sacoba.vista.PanelConFondo panelConFondo376;
    private sacoba.vista.PanelConFondo panelConFondo377;
    private sacoba.vista.PanelConFondo panelConFondo378;
    private sacoba.vista.PanelConFondo panelConFondo379;
    private sacoba.vista.PanelConFondo panelConFondo38;
    private sacoba.vista.PanelConFondo panelConFondo380;
    private sacoba.vista.PanelConFondo panelConFondo381;
    private sacoba.vista.PanelConFondo panelConFondo382;
    private sacoba.vista.PanelConFondo panelConFondo383;
    private sacoba.vista.PanelConFondo panelConFondo384;
    private sacoba.vista.PanelConFondo panelConFondo385;
    private sacoba.vista.PanelConFondo panelConFondo386;
    private sacoba.vista.PanelConFondo panelConFondo387;
    private sacoba.vista.PanelConFondo panelConFondo388;
    private sacoba.vista.PanelConFondo panelConFondo389;
    private sacoba.vista.PanelConFondo panelConFondo39;
    private sacoba.vista.PanelConFondo panelConFondo390;
    private sacoba.vista.PanelConFondo panelConFondo391;
    private sacoba.vista.PanelConFondo panelConFondo392;
    private sacoba.vista.PanelConFondo panelConFondo393;
    private sacoba.vista.PanelConFondo panelConFondo394;
    private sacoba.vista.PanelConFondo panelConFondo395;
    private sacoba.vista.PanelConFondo panelConFondo396;
    private sacoba.vista.PanelConFondo panelConFondo397;
    private sacoba.vista.PanelConFondo panelConFondo398;
    private sacoba.vista.PanelConFondo panelConFondo399;
    private sacoba.vista.PanelConFondo panelConFondo4;
    private sacoba.vista.PanelConFondo panelConFondo40;
    private sacoba.vista.PanelConFondo panelConFondo400;
    private sacoba.vista.PanelConFondo panelConFondo401;
    private sacoba.vista.PanelConFondo panelConFondo402;
    private sacoba.vista.PanelConFondo panelConFondo403;
    private sacoba.vista.PanelConFondo panelConFondo404;
    private sacoba.vista.PanelConFondo panelConFondo405;
    private sacoba.vista.PanelConFondo panelConFondo41;
    private sacoba.vista.PanelConFondo panelConFondo42;
    private sacoba.vista.PanelConFondo panelConFondo43;
    private sacoba.vista.PanelConFondo panelConFondo44;
    private sacoba.vista.PanelConFondo panelConFondo45;
    private sacoba.vista.PanelConFondo panelConFondo46;
    private sacoba.vista.PanelConFondo panelConFondo47;
    private sacoba.vista.PanelConFondo panelConFondo48;
    private sacoba.vista.PanelConFondo panelConFondo49;
    private sacoba.vista.PanelConFondo panelConFondo5;
    private sacoba.vista.PanelConFondo panelConFondo50;
    private sacoba.vista.PanelConFondo panelConFondo51;
    private sacoba.vista.PanelConFondo panelConFondo52;
    private sacoba.vista.PanelConFondo panelConFondo53;
    private sacoba.vista.PanelConFondo panelConFondo54;
    private sacoba.vista.PanelConFondo panelConFondo55;
    private sacoba.vista.PanelConFondo panelConFondo56;
    private sacoba.vista.PanelConFondo panelConFondo57;
    private sacoba.vista.PanelConFondo panelConFondo58;
    private sacoba.vista.PanelConFondo panelConFondo59;
    private sacoba.vista.PanelConFondo panelConFondo6;
    private sacoba.vista.PanelConFondo panelConFondo60;
    private sacoba.vista.PanelConFondo panelConFondo61;
    private sacoba.vista.PanelConFondo panelConFondo62;
    private sacoba.vista.PanelConFondo panelConFondo63;
    private sacoba.vista.PanelConFondo panelConFondo64;
    private sacoba.vista.PanelConFondo panelConFondo65;
    private sacoba.vista.PanelConFondo panelConFondo66;
    private sacoba.vista.PanelConFondo panelConFondo67;
    private sacoba.vista.PanelConFondo panelConFondo68;
    private sacoba.vista.PanelConFondo panelConFondo69;
    private sacoba.vista.PanelConFondo panelConFondo7;
    private sacoba.vista.PanelConFondo panelConFondo70;
    private sacoba.vista.PanelConFondo panelConFondo71;
    private sacoba.vista.PanelConFondo panelConFondo72;
    private sacoba.vista.PanelConFondo panelConFondo73;
    private sacoba.vista.PanelConFondo panelConFondo74;
    private sacoba.vista.PanelConFondo panelConFondo75;
    private sacoba.vista.PanelConFondo panelConFondo76;
    private sacoba.vista.PanelConFondo panelConFondo77;
    private sacoba.vista.PanelConFondo panelConFondo78;
    private sacoba.vista.PanelConFondo panelConFondo79;
    private sacoba.vista.PanelConFondo panelConFondo8;
    private sacoba.vista.PanelConFondo panelConFondo80;
    private sacoba.vista.PanelConFondo panelConFondo81;
    private sacoba.vista.PanelConFondo panelConFondo82;
    private sacoba.vista.PanelConFondo panelConFondo83;
    private sacoba.vista.PanelConFondo panelConFondo84;
    private sacoba.vista.PanelConFondo panelConFondo85;
    private sacoba.vista.PanelConFondo panelConFondo86;
    private sacoba.vista.PanelConFondo panelConFondo87;
    private sacoba.vista.PanelConFondo panelConFondo88;
    private sacoba.vista.PanelConFondo panelConFondo89;
    private sacoba.vista.PanelConFondo panelConFondo9;
    private sacoba.vista.PanelConFondo panelConFondo90;
    private sacoba.vista.PanelConFondo panelConFondo91;
    private sacoba.vista.PanelConFondo panelConFondo92;
    private sacoba.vista.PanelConFondo panelConFondo93;
    private sacoba.vista.PanelConFondo panelConFondo94;
    private sacoba.vista.PanelConFondo panelConFondo95;
    private sacoba.vista.PanelConFondo panelConFondo96;
    private sacoba.vista.PanelConFondo panelConFondo97;
    private sacoba.vista.PanelConFondo panelConFondo98;
    private sacoba.vista.PanelConFondo panelConFondo99;
    private sacoba.vista.TransparentTextArea transparentTextArea1;
    private sacoba.vista.TransparentTextArea txtBienvenidos;
    private sacoba.vista.TransparentTextArea txtSigue;
    // End of variables declaration//GEN-END:variables
}
