/*
 *  Sistema de Asistencia de Control Bancario
 *  SACOBA
 *  
 *  Marcela Cascante Quiros
 *  Diego Delgado Cerdas
 *  Alejandro Loaiza Arguedas
 *  Jose David Mora Loria
 */
package sacoba.cliente.vista;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.text.MaskFormatter;
import sacoba.vista.VentanaBase;

/**
 *
 * @author ulacit
 */
public class PuertaView extends VentanaBase {

    /**
     * Creates new form PuertaView
     */
    public PuertaView() {
        initComponents();
        //setSize(VentanaBase.ANCHO, VentanaBase.ALTO);

        try {
            MaskFormatter mascara_cedula = new MaskFormatter("#-####-####");
            txtCedula.setMask(mascara_cedula);
        } catch (ParseException ex) {
            Logger.getLogger(PuertaView.class.getName()).log(Level.SEVERE, null, ex);
        }

        ButtonGroup options = new ButtonGroup();
        options.add(jbop1);
        options.add(jbop2);
        options.add(jbop3);
        options.add(jbop4);
        options.add(jbop5);
        options.add(jbop6);
        options.add(jbop7);
        options.add(jbop8);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new sacoba.vista.PanelConFondo("fondo_panel.png");
        jLabel1 = new javax.swing.JLabel();
        panelClientes = new sacoba.vista.PanelConFondo("fondo_panel.png");
        lblTituloCuentas = new javax.swing.JLabel();
        lblTituloPlataforma = new javax.swing.JLabel();
        lblTituloTramites = new javax.swing.JLabel();
        lblPlataforma = new javax.swing.JLabel();
        lblPlataforma1 = new javax.swing.JLabel();
        lblPlataforma2 = new javax.swing.JLabel();
        panelUsuario = new sacoba.vista.PanelConFondo("fondo_panel.png");
        lblCedula = new javax.swing.JLabel();
        txtCedula = new sacoba.vista.TransparentFormattedTextField();
        lblCedula1 = new javax.swing.JLabel();
        panelUsuarioIzq = new sacoba.vista.PanelConFondo("fondo_panel.png");
        jbop4 = new javax.swing.JRadioButton();
        jbop1 = new javax.swing.JRadioButton();
        jbop2 = new javax.swing.JRadioButton();
        jbop3 = new javax.swing.JRadioButton();
        panelUsuarioDer2 = new sacoba.vista.PanelConFondo("fondo_panel.png");
        jbop8 = new javax.swing.JRadioButton();
        jbop7 = new javax.swing.JRadioButton();
        panelUsuarioDer1 = new sacoba.vista.PanelConFondo("fondo_panel.png");
        jbop6 = new javax.swing.JRadioButton();
        jbop5 = new javax.swing.JRadioButton();
        lblContinuar = new javax.swing.JLabel();
        btnContinuar = new sacoba.vista.PanelConFondo("flecha.png");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 650));
        setMinimumSize(new java.awt.Dimension(950, 650));
        setSize(new java.awt.Dimension(950, 650));

        jLabel1.setFont(LETRA_TITULO);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTitulo.add(jLabel1);
        jLabel1.setBounds(10, 0, 530, 50);

        panelClientes.setEnabled(false);

        lblTituloCuentas.setFont(LETRA_TEXTO_1);
        lblTituloCuentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloCuentas.setText("Cuentas:");
        lblTituloCuentas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelClientes.add(lblTituloCuentas);
        lblTituloCuentas.setBounds(20, 320, 250, 30);

        lblTituloPlataforma.setFont(LETRA_TEXTO_1);
        lblTituloPlataforma.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloPlataforma.setText("Plataforma:");
        lblTituloPlataforma.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelClientes.add(lblTituloPlataforma);
        lblTituloPlataforma.setBounds(20, 60, 250, 30);

        lblTituloTramites.setFont(LETRA_TEXTO_1);
        lblTituloTramites.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloTramites.setText("Trámites:");
        lblTituloTramites.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelClientes.add(lblTituloTramites);
        lblTituloTramites.setBounds(20, 190, 250, 30);

        lblPlataforma.setFont(LETRA_TITULO);
        lblPlataforma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlataforma.setText("0");
        lblPlataforma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelClientes.add(lblPlataforma);
        lblPlataforma.setBounds(20, 340, 240, 100);

        lblPlataforma1.setFont(LETRA_TITULO);
        lblPlataforma1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlataforma1.setText("0");
        lblPlataforma1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelClientes.add(lblPlataforma1);
        lblPlataforma1.setBounds(20, 80, 240, 100);

        lblPlataforma2.setFont(LETRA_TITULO);
        lblPlataforma2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlataforma2.setText("0");
        lblPlataforma2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelClientes.add(lblPlataforma2);
        lblPlataforma2.setBounds(20, 210, 240, 100);

        lblCedula.setFont(LETRA_TEXTO_1);
        lblCedula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCedula.setText("Seleccione una opción:");
        lblCedula.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelUsuario.add(lblCedula);
        lblCedula.setBounds(40, 90, 270, 30);

        txtCedula.setToolTipText("Ingrese su cédula");
        txtCedula.setFont(LETRA_TEXTO_3);
        panelUsuario.add(txtCedula);
        txtCedula.setBounds(240, 50, 190, 30);

        lblCedula1.setFont(LETRA_TEXTO_2);
        lblCedula1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCedula1.setText("Digite su cédula:");
        lblCedula1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelUsuario.add(lblCedula1);
        lblCedula1.setBounds(80, 50, 150, 30);

        jbop4.setFont(LETRA_TEXTO_3);
        jbop4.setText("Transferencia");
        jbop4.setToolTipText("Seleccione el proceso deseado");
        panelUsuarioIzq.add(jbop4);
        jbop4.setBounds(20, 110, 190, 30);

        jbop1.setFont(LETRA_TEXTO_3);
        jbop1.setText("Cambio de moneda");
        jbop1.setToolTipText("Seleccione el proceso deseado");
        panelUsuarioIzq.add(jbop1);
        jbop1.setBounds(20, 20, 190, 30);

        jbop2.setFont(LETRA_TEXTO_3);
        jbop2.setText("Depositar a cuenta");
        jbop2.setToolTipText("Seleccione el proceso deseado");
        panelUsuarioIzq.add(jbop2);
        jbop2.setBounds(20, 50, 190, 30);

        jbop3.setFont(LETRA_TEXTO_3);
        jbop3.setText("Pagar servicio");
        jbop3.setToolTipText("Seleccione el proceso deseado");
        panelUsuarioIzq.add(jbop3);
        jbop3.setBounds(20, 80, 190, 30);

        panelUsuario.add(panelUsuarioIzq);
        panelUsuarioIzq.setBounds(40, 130, 230, 160);

        jbop8.setFont(LETRA_TEXTO_3);
        jbop8.setText("Otro");
        jbop8.setToolTipText("Seleccione el proceso deseado");
        panelUsuarioDer2.add(jbop8);
        jbop8.setBounds(20, 30, 190, 30);

        jbop7.setFont(LETRA_TEXTO_3);
        jbop7.setText("Cuentas");
        jbop7.setToolTipText("Seleccione el proceso deseado");
        panelUsuarioDer2.add(jbop7);
        jbop7.setBounds(20, 0, 190, 30);

        panelUsuario.add(panelUsuarioDer2);
        panelUsuarioDer2.setBounds(280, 220, 230, 60);

        jbop6.setFont(LETRA_TEXTO_3);
        jbop6.setText("Tarjetas");
        jbop6.setToolTipText("Seleccione el proceso deseado");
        panelUsuarioDer1.add(jbop6);
        jbop6.setBounds(20, 30, 190, 30);

        jbop5.setFont(LETRA_TEXTO_3);
        jbop5.setText("Préstamos");
        jbop5.setToolTipText("Seleccione el proceso deseado");
        panelUsuarioDer1.add(jbop5);
        jbop5.setBounds(20, 0, 190, 30);

        panelUsuario.add(panelUsuarioDer1);
        panelUsuarioDer1.setBounds(280, 140, 230, 60);

        lblContinuar.setFont(LETRA_TEXTO_2);
        lblContinuar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContinuar.setText("Continuar");
        lblContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelUsuario.add(lblContinuar);
        lblContinuar.setBounds(260, 290, 150, 50);
        panelUsuario.add(btnContinuar);
        btnContinuar.setBounds(420, 290, 80, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(panelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sacoba.vista.PanelConFondo btnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jbop1;
    private javax.swing.JRadioButton jbop2;
    private javax.swing.JRadioButton jbop3;
    private javax.swing.JRadioButton jbop4;
    private javax.swing.JRadioButton jbop5;
    private javax.swing.JRadioButton jbop6;
    private javax.swing.JRadioButton jbop7;
    private javax.swing.JRadioButton jbop8;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedula1;
    private javax.swing.JLabel lblContinuar;
    private javax.swing.JLabel lblPlataforma;
    private javax.swing.JLabel lblPlataforma1;
    private javax.swing.JLabel lblPlataforma2;
    private javax.swing.JLabel lblTituloCuentas;
    private javax.swing.JLabel lblTituloPlataforma;
    private javax.swing.JLabel lblTituloTramites;
    private sacoba.vista.PanelConFondo panelClientes;
    private sacoba.vista.PanelConFondo panelTitulo;
    private sacoba.vista.PanelConFondo panelUsuario;
    private sacoba.vista.PanelConFondo panelUsuarioDer1;
    private sacoba.vista.PanelConFondo panelUsuarioDer2;
    private sacoba.vista.PanelConFondo panelUsuarioIzq;
    private sacoba.vista.TransparentFormattedTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
